### ISSUE TITLE
let me choose langauge please

### ISSUE THREAD

**Issue by shinji2009** [Robbendebiene/Gesturefy#113]
hi
let user have choice to set langauge please, i'd like to have settings in english. thanks.

**Comment by Robbendebiene** [comment]
As far as I know, there is no way to do this. You'll have to change the whole browser UI language.

**Comment by ScienceDiscoverer** [comment]
WOW, this really surprised me. Firefox devs, knowing that many addons struggle with localization, still didn't allow for a simple language switch for addons? Unfathomable! Even stranger, still, I can't find any bug/suggestion reports fired up to fix this situation...

I have a little idea about how to partially solve this problem for Gesturefy. If some language have less than 100% translated and checked, just stick to English. This way we can avoid partial translations, at least. Or is it not possible due to API also?
