### ISSUE TITLE
Open URL from clipboard - action

### ISSUE THREAD

**Issue by scar99** [Robbendebiene/Gesturefy#144]
Firegestures was able, open the URL from clipboard.
Is it possible to built this in?

Thank you.

**Comment by scar99** [comment]
Firegestures was able, open the URL from clipboard..
Is it possible to built this in?
Thank you.

**Comment by YuriiBar** [comment]
And I like that

**Comment by Matthias030** [comment]
Thx for creating Gesturefy :-)

It would be really great to have this feature. Use this with FireGestures nearly all days.

Matthias

**Comment by Robbendebiene** [comment]
While implementing this functionality, I have come up with some questions.

1. Should the action only work if the clipboard contains a plain URL or should it also work for texts which contain an URL like in the example below which then would open github.com? If the second version is prefered, what happens if the text contains multiple URLs?

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim https://github.com/ veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

2. Should it open the URL in a new tab or in the current one?

**Comment by Matthias030** [comment]
Sorry for the delay.

1. It should be ok to use a plain URL instead of having a text contains an URL.
2. Yes, please open a new Tab for that :-)

**Comment by Robbendebiene** [comment]
Added in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0)

**Comment by ldgbc** [comment]
Anyone having issue with using this Gesture? It not doing anything for me.
