### ISSUE TITLE
Feature Request - Middle Click Rocker Combos

### ISSUE THREAD

**Issue by EiriMasami** [Robbendebiene/Gesturefy#170]
It'd be nice to have more options for rocker gestures involving middle click, e.g. right click + middle click. I believe throwing middle click into the mix would bring the total available rocker gestures up to six, which would be more than enough for basic navigation.

**Comment by Robbendebiene** [comment]
Nice idea. The only downside of this is, that I would have to supress the middle mouse autoscrolling thingy.
Because in the moment the user presses the middle mouse button, I don't know if the user wants to perform a rocker gesture or not.

**Comment by Robbendebiene** [comment]
I delayed the decision for this issue for a long time, since it has a valid use case. But at the end I've decided against it for the following reasons:
1. The problem I've mentioned in my comment above
2. Rocker gestures are only one little extra functionality in Gesturefy and not the main part of the program
3. Low cost-benefit ratio (from a developer point of view)

Because of that an extra add-on specifically designed for rocker gestures should fill this gap.
