### ISSUE TITLE
gesture work only on page with 'www' in url

### ISSUE THREAD

**Issue by progserega** [Robbendebiene/Gesturefy#172]
gesture work only on page with 'www' in url. On other page gesture not work, not show text gesture - fully not working.
Lunux ubuntu 16.0.4, firefox 57.0,  settings with middle button.

**Comment by uegajde** [comment]
> work only on the page with 'www' in url

it is out of mind for me
does Gesturefy not work in `https://github.com` either?

or 
Do you mean Gesturefy only works in websites but not in Firefox internal pages such as new tab (about:newtab), settings, addons and so on? 
if so,
this is caused by the limitation of WebExtension.
WebExtension is different from previous API in the concern of security and compatibility.
As a result, addons cannot access Firefox internal things and protected website (such as AMO)
please read the readme or description on AMO
 also, this problem is already discussed, you can read previous issues #5 #6 #157

**Comment by progserega** [comment]
>  it is out of mind for me
> does Gesturefy not work in https://github.com either?

Hmm. I try again (at next day), and all work success. Today Gesturefy work in https://github.com. 
I can not repeat this bug today.
Sorry! I think, We can close this bug.
