### ISSUE TITLE
Did not work on start page

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#179]
on this [page](http://joxi.ru/GrqKNGgSND69a2) gestures did not work

**Comment by KES777** [comment]
on [this](https://addons.mozilla.org/en-US/firefox/addon/flash-gestures/) page gestures do not work too

**Comment by KES777** [comment]
and [this](about:addons)

**Comment by uegajde** [comment]
you should read the readme or description on AMO

> The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

this is not the addons' fault
just all new addons based on WebExtension cannot work on there pages.

this problem appears almost everyday.
don't you search the existing issues before open a new issue?
this problem is already discussed, you can read previous issues #5 #6 #157 (and more...)

**Comment by KES777** [comment]
this is very unhandy when getures did not work for just opened tab

**Comment by soc** [comment]
@KES777 See https://github.com/Robbendebiene/Gesturefy/issues/5#issuecomment-546697754. Hope this helps.
