### ISSUE TITLE
Close behavior after open link in new foreground tab

### ISSUE THREAD

**Issue by bfreuden** [Robbendebiene/Gesturefy#187]
As is it my first post here, let me first thank you for your hard work producing this excellent add-on! 

It looks like there is a glitch with the "open link in new foreground tab" gesture. When you open such a tab then close it using mouse gestures, Firefox does not display the tab the open gesture was initiated from: instead you return to the tab on the right of the closed one. 

For example if you have 2 tabs (bold itatic has the focus): **_A_**, B
Then you open a link in new foreground tab (using the mouse gesture): A, **_C_**, B
Then you close C (using the mouse gesture): A, **_B_**
I was expecting: **_A_**, B

The strange thing is getting back to A is what happens when using the "open link in new background tab" gesture: **_A_**, C, B
Selecting the C tab: A, **_C_**, B
Closing C (using the mouse gesture): **_A_**, B

Gesturefy 1.1.17
Firefox 57.0.1 (64 bits)
Windows 10

**Comment by Robbendebiene** [comment]
> As is it my first post here, let me first thank you for your hard work producing this excellent add-on!

Thank you for your commendation and the detailed description.

> The strange thing is getting back to A is what happens when using the "open link in new background tab" 
> gesture: **_A_**, C, B
> Selecting the C tab: A, **_C_**, B
> Closing C (using the mouse gesture): **_A_**, B

This happens to me when B was not opened via the "open link in new background tab" gesture.

Otherwise it's always the last opened tab which will switch to the "parent" tab unless you switched to another tab before closing the last one:

B & C opened via gesture: **_A_**, B, C
Selecting the C tab: A, B, **_C_**
Closing C (using the mouse gesture): **_A_**, B

So from my point of view, this is the actual bug, because Firefox is always switching to the right tab.

**Comment by rodalpho** [comment]
I find this incredibly annoying also and actually installed another addon just to fix this problem. Would love if you could address it in Gesturefy!

https://addons.mozilla.org/en-US/firefox/addon/focuslastselectedtab/

**Comment by Robbendebiene** [comment]
@rodalpho Please visit the advanced settings of the "remove tab" action. It's already implemented.

**Comment by rodalpho** [comment]
Thanks-- actually it works properly at work on my mac. Here's what I think happened. I use the R+L chord to remove tabs. That remove tab focus setting is kept under mouse gestures, so I didn't have it set at home. I'll confirm when I get home.

I believe a lot of my confusion comes from how the addon is configured, going from mapping gestures to actions rather than the reverse. It might be better to do the reverse, have the user input a gesture/chord/wheel gesture and then select the action to map to it from a dropdown, same as on the "extras" page. Then all the various switches like tab focus on removing tabs could be kept separate and easily accessible. Just a thought.

**Comment by Robbendebiene** [comment]
@rodalpho I agree and I already have plans to improve this, but it will take some time.

**Comment by bfreuden** [comment]
> Please visit the advanced settings of the "remove tab" action. It's already implemented.

I should have taken a closer look at the options before posting... I'm sorry.
Just tested the "previous" settings and it works like a charm. Thank you!

**Comment by rodalpho** [comment]
I just got home and tested this out on windows. It's weird, and I have no way to explain it. 

I set it to "previous" under remove tab and it totally didn't work, selected right tab every time. Tried removing the FLST addon and restarting Fx, didn't fix the problem. Then I changed it to left, didn't work, still right. Back to previous, didn't work. Back to left, restarted Fx, and then... for some reason... it started working. Back to previous, works fine now.

Bizarre!!

**Comment by Robbendebiene** [comment]
> Also, it only works when the tab is closed via mouse gesture. Would it be possible to extend that to clicking on the close tab button also, or would you consider that out of scope for the addon? I expect anyone setting that option would prefer it to work consistently across the browser.


Sorry, but as you said, this is out of scope.
