### ISSUE TITLE
Context menu is opened for every gesture

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#19]
Context menu is opened for every gesture when when I release the mouse button.
Gesturefy 1.0.4 on Firefox 56 beta2 and last Nightly on Windows 7.
Back to previous 1.0.3 version.

**Comment by Robbendebiene** [comment]
Thats bad :| I was only able to test it on my Linux system, maybe I broke something for windows. Can you please test if this also happens on the latest stable release?

**Comment by Robbendebiene** [comment]
I think it will still not work in the stable release, I'll push a fix in some minutes, would be great if you can test this for me so I can get the patch out tonight, because I'm away from my laptop for 2 weeks.
To test it for me:
0) disable the currently running Gesturefy addon
1) download the new one https://github.com/Robbendebiene/Gesturefy/archive/master.zip
2) unzip the zip file somewhere
3) go to "about:debugging" in your firefox browser, click on "Load addon temporary" or something like this and go to the unzipped folder
4) select the "manifest.json" file in the src folder

**Comment by happysurf** [comment]
Yes also in stable release is broken, after remove the old version I have loaded the new one in master.zip but unfortunately the problem is still here.

**Comment by Robbendebiene** [comment]
ok next try, please download and try it again

**Comment by happysurf** [comment]
Same problem.

**Comment by Robbendebiene** [comment]
hmm, I uploaded another version. I hope this works

**Comment by Robbendebiene** [comment]
If not I have another idea, I think I got it

**Comment by happysurf** [comment]
No, same problem again.

**Comment by Robbendebiene** [comment]
ok, now i'm confident. Please try one more time

**Comment by happysurf** [comment]
Bingo, now works.
Great work my friend.

**Comment by Robbendebiene** [comment]
Ahh nice, thank you very much for your help and lightning quick report :D
I hope I did not brake anything else and will submit the fix to mozilla soon.

**Comment by happysurf** [comment]
You are welcome.
