### ISSUE TITLE
Feature request : Option to enable/disable specific gestures

### ISSUE THREAD

**Issue by Betsy25** [Robbendebiene/Gesturefy#209]
Hi,

This is a surprisingly wonderfully working extension, but would it make sense if the user was able to enable/disable specific gestures ? Like using a checkmark before them in the gesture list ?

**Comment by Robbendebiene** [comment]
Hey. Why don't you just delete them, either by selecting and removing the gesture encoding or by pressing the record button (circle) > clear button?

**Comment by bubblefoil** [comment]
I would suggest perhaps adding a X icon next to the O for recording. It may not be obvious that you can type/erase the arrows or that there is a clear button in the corner of the recording canvas.
Also I am personally in favour of tooltips on UI components. The design may stay purely graphic but it can still be clarified what happens if I press this or that.

**Comment by Robbendebiene** [comment]
A real delete button will be implemented as a part of this feature https://github.com/Robbendebiene/Gesturefy/issues/197
Therefore I'm closing this one.
