### ISSUE TITLE
Right-click gestures not caught when using touchscreen on Windows 10

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [Robbendebiene/Gesturefy#229]
When using Firefox 57.0.4 on Windows 10 x64, tapping and holding on a touchscreen (triggering a right-click) and dragging along the touchscreen, Firefox continues to scroll the page and Gesturefy doesn't attempt to capture gestures.

System information:
* Firefox version: 57.0.4 x64
* OS: Windows 10 Education x64, version 1709

Reproduction steps:
0. Acquire a touchscreen-enabled device running Windows 10
1. Configure Gesturefy to start on right-click via the settings
2. Open a Gesturefy-capable page (i.e. not `*.mozilla.org`, `about:*`, etc.)
3. Tap and hold on the screen until the black/white box appears (indicating right-click)
4. While holding, drag across the screen. Notice that gestures are not being picked up.

**Comment by Robbendebiene** [comment]
Since I do not have a touch screen I'm not able to reproduce this. Also there already is another issue adressing a similar or even the same problem on microsoft surface #98.
Does the context menu on a touch devices open on hold or on release?

It could also be helpfull if you could execute the code below on an example page like Github. You do so by pressing `Ctrl + Shift + K` to open the console. Just copy and paste in the snippet and press enter. After that please try to draw a gesture and post the console output here (if any).

```
window.addEventListener("mousedown", (e) => {
  console.log("down", e.button, e.buttons);
});
window.addEventListener("mouseup", (e) => {
  console.log("up", e.button, e.buttons);
});
window.addEventListener("click", (e) => {
  console.log("click", e.button, e.buttons);
});
window.addEventListener("contextmenu", (e) => {
  console.log("menu", e.button, e.buttons);
});

```
