### ISSUE TITLE
"Link to background tab" gesture does not change the link color

### ISSUE THREAD

**Issue by succulent-headcrab** [Robbendebiene/Gesturefy#230]
When opening a background tab using the builtin `CTRL+Click`, the clicked link immediately changes color to the "visited" color (ie Blue->Purple). When using the `Link to background tab` gesture, the link color is not changed until the page is reloaded.
I would expect that the `Link to background tab` gesture would have the same behaviour as the builtin `CTRL+Click` action.

Gesturefy, Version: 1.1.17
Firefox 57.0.4 (64-bit)

**Comment by Robbendebiene** [comment]
Sorry, but I'm not aware of any good solution.

If someone else knows a decent solution for this, I will certainly implement it, but since this is a very minor problem I will probably close the issue.

This also might  be a Firefox related issue. Since it's working correctly, when I'm opening the same link twice with the `Link to background tab` action.

**Comment by succulent-headcrab** [comment]
I can also confirm that opening the link twice does in fact trigger the color change for me. 

> I will probably close the issue.

That's fair. The only real life issue it causes is that I tend to lose my place when I'm opening and switching between a lot of new tabs from search results or the like. I had hoped it was due to some minor oversight or change in Firefox. Not the end of the world.

Thanks

**Comment by Robbendebiene** [comment]
Alright, thank you for understanding!
