### ISSUE TITLE
Restore Tab not working as intended

### ISSUE THREAD

**Issue by Jollemj** [Robbendebiene/Gesturefy#236]
I have latest FF and Gesturefy but the restore tab does not restore the last closed tab.
If you have multiple FF windows open it will sort of randomly restore other tabs and not the most recently closed tab

**Comment by Robbendebiene** [comment]
Hey, please provide more detailed steps describing how to reproduce the problem.

Maybe by "randomly" you mean that it will restore the last tab regardingless to the window it belongs to? So for example: you close a tab in window 1 and another one in window 2. If you then execute the gesture in window 1 (or 2) it will restore the closed tab of window 2 (because this was the last recently closed tab). In short, It will take the last closed tab of all windows and not per window.

**Comment by Itchiii** [comment]
Maybe you can specify a checkbox where you can choose if you want to include all the windows or just the active one (in which the gesture was executed)?

**Comment by Robbendebiene** [comment]
In Gesturefy 2.0.0 there is now an advanced option when you set the "Restore Tab" command that allows you to restore tabs of the current window only.

**Comment by limes007** [comment]
I have version 2.0.4, where can I find this option? I have the same problem and surely the impression, this is random. I cannot reproduce it up to now, but it sucks me from time to time. So I want to try the new option, maybe this would help.

**Comment by Robbendebiene** [comment]
> where can I find this option?

Click on the related Gesture in the add-on Options page -> click on the command -> choose the "Restore Tab" command.

> I cannot reproduce it up to now, but it sucks me from time to time. So I want to try the new option, maybe this would help.

It is annoying me too but I cannot do much about it. I hope some of the Mozilla devs will take up this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1408575) in the near futurer.

**Comment by limes007** [comment]
Ok, a well hidden option ;-) Unfortunately it was already activated...

As I see, this is a bug in Firefox instead of Gesturefy. Not good, but good to know. Thanks and all the best.
