### ISSUE TITLE
Feature Request - Gestures Suggestion

### ISSUE THREAD

**Issue by vienngoc9** [Robbendebiene/Gesturefy#257]
Having many gestures is hard on the brain (specifically mine) so some suggestions when gesturing would be really nice.
Maybe it'd look like this:
(image showing suggestions when you've made one RIGHT)
![](https://user-images.githubusercontent.com/36404952/36469094-a2c9606a-1718-11e8-8c7e-02949d8f88b1.png)

**Comment by Robbendebiene** [comment]
This is definitely an interesting idea. I will look into it after I released the next major version of Gesturefy.

**Comment by beelze** [comment]
Interesting idea – gestures are convenient and easy to use, but hard to remember sometimes. But what if I forgot direction of first move? As an alternative approach, it would be nice to have an ability to qickly view some kind of summary (all assigned gestures), activated by hotkey or another gesture.

**Comment by bubblefoil** [comment]
There is an interesting plugin for IntelliJ IDEA called Key Promoter X. When user triggers any IDE feature/action which has a keyboard shortcut assigned to it the Key Promoter shows a short popup with the shortcut.
It a browser plugin is able to capture user actions like this, it might be really useful to remind users of the assigned gesture in a similar way. I could imagine this would be useful for actions from browser's popup menu or toolbar buttons. Not so much for keyboard shortcuts as those might be used instead of gestures intentionally.

**Comment by Robbendebiene** [comment]
This feature request is now obsolete with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
