### ISSUE TITLE
1.2 make firefox  crash

### ISSUE THREAD

**Issue by OpenWeb321** [Robbendebiene/Gesturefy#260]
RT
https://crash-stats.mozilla.com/report/index/b5b466f4-fd09-461c-a64c-18d200180228
https://crash-stats.mozilla.com/report/index/39b67e1c-97ef-48b7-8763-703960180228
https://crash-stats.mozilla.com/report/index/332eaa66-815b-4c9e-b3e9-dcd2d0180228

**Comment by Robbendebiene** [comment]
First of all, please provide more information as described [here.](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md) Second, I'm pretty sure that there is nothing I can do about it, because it's nearly impossible to crash the browser intentionally with the new api. Since you are using the beta version of Firefox this might be a known bug and will get fixed soon. If not you should contact Mozilla.
