### ISSUE TITLE
"Image to tab" - does not work for data: urls

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#262]
I don't sure if is a my problem or not  but on some sites this gesture doesn't work.
Image example link:
https://prnt.sc/ilrhn1

Firefox 59beta 64bit on W10.

**Comment by Robbendebiene** [comment]
This is a protection by the website itself. You'll notice that even right click and "View Image" won't work. This is because there is a hidden image before the image which leads you to the same site over and over again.

However you can still get the image source with some tricks, here it is: https://image.prntscr.com/image/hWDjxhETQWie8e3cjx-rOg.png
 :)

**Comment by happysurf** [comment]
> You'll notice that even right click and "View Image" won't work.

Strange, in my case works also with Firefox in safe mode.

**Comment by Robbendebiene** [comment]
Oh, I should have turned off uMatrix.. So in this case it's an api limitation, because the image url of the overlaying image is a so called "data url" which cannot be opened via the new [webextensions api for security reasons](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create)

**Comment by Robbendebiene** [comment]
I'm closing this, since it is unlikely that Mozilla will allow extensions to load foreign data urls.
