### ISSUE TITLE
Problems when used together with add-on owl

### ISSUE THREAD

**Issue by Jeansen** [Robbendebiene/Gesturefy#268]
I am using the addon owl together with Gesturefy. But with owl enabled the response time of Gesturefy is very slow. In addition the gesture line drawn is not visible. I am not sure if this is a sole problem with owl, Gesturefy or both because each add-on works flawlessly on its own for me.

**Comment by Robbendebiene** [comment]
In theory it's possible that they conflict with each other, however after some short tests I did not encountered any of the problems you've described.

Can you narrow down the problem to a particular website or addon configuration?

**Comment by Jeansen** [comment]
Well, I think I narrowed it down. If I enable owl, and have a web page set to dark layout, Gesturefy does not work. That is, I do not see the gesture line  and additional HUD. If I disable owl for a web page, Gesturefy works as expected. I guess the color overwrites interfere then. 

Question now is, if this is something that can be caught in Gesturefy to react accordingly, or in owl. Or, it is simply not possible to use those together because of the way owl and Gesturefy work.

**Comment by Robbendebiene** [comment]
Since I cannot reproduce the problem I can only vaguely say that there is currently nothing I can do. At least I did everything thats possible on the implementartion side to prevent the Gesturefy HUD from beeing restyled.
However you may be able to fix this by editing and adjusting the dark theme.

Mozilla is working on a new API which will give me the oportunity to separate my content from the webpage, which will also solve the issue, but it will take some time untill the API is implemented.

**Comment by Jeansen** [comment]
No problem, I totally understand. I'll wait until the new API is implemented. And thanks for your effort in making this plug-in! :smiley:

**Comment by Robbendebiene** [comment]
No problem, thank you for your understanding :)
