### ISSUE TITLE
Wheel Gestures

### ISSUE THREAD

**Issue by yulelong** [Robbendebiene/Gesturefy#27]
AS in Firegestures, Wheel Gestures (Scroll wheel with holding right-click) make it quite convenient to switch to any tab since Mouse Gestures (Move mouse with holding right-click) can only switch to an adjacent tab.
Can you add such feature to Gesturefy please?

**Comment by Robbendebiene** [comment]
Its on the list, but the feature you request wont work as fluently as you know it from fire gestures especially if you switch to an unloaded tab you will have to wait until it's partially loaded to perform the next wheel gesture. This is because with the new API I can only listen to mouse or keyboard events in the website directly and not in the global firefox "window".

**Comment by Robbendebiene** [comment]
done: 3deb910f14d070c969c369a35230ce3f94448a0d
