### ISSUE TITLE
'New private window' gesture opens a normal new tab page

### ISSUE THREAD

**Issue by maldis018** [Robbendebiene/Gesturefy#288]
### Steps to Reproduce
The following was done on a fresh profile

1. Install Gesturefy
2. Record gesture for new private window
3. Execute the gesture
4. The new Firefox window will briefly flash purple before it will display the New Tab page instead of the private browsing new tab. Subsequent tabs in the same window are unaffected. 

Note the private window badge on the new tab page in the screenshot below

![2018-05-01 18_22_44 new tab](https://user-images.githubusercontent.com/38895070/39496499-b6ce9c4e-4d6c-11e8-9049-2f2918f020cd.png)

- Operating system: Windows 10 N Pro x64 1709
- Firefox version: 59.0.3
- Gesturefy version: 1.2.2

**Comment by Robbendebiene** [comment]
Thanks for the detailed report.
Unfortunatly I cannot fix this problem, because it seems to be an "error" in the API I'm using which is provided by Firefox. You could create a [bug ticket on bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi#h=dupes%7CToolkit). There it might be helpfull to also attach the code which is executed by the "NewPrivateWindow" action:
```
    chrome.windows.create({
      incognito: true
    });
```

**Comment by Robbendebiene** [comment]
Does this problem still occur?

**Comment by maldis018** [comment]
No. It got fixed when Mozilla changed the splash page some months ago. I
don't remember exactly.

**Comment by Robbendebiene** [comment]
Thanks for the reply. I'm closing this issue then.
