### ISSUE TITLE
"Open Homepage" gesture recognised but not doing anything

### ISSUE THREAD

**Issue by LlamaFarmerama** [Robbendebiene/Gesturefy#305]
Firefox updated to 61.0 just now, which is when the problem started occurring. When I have any webpage open, using my gesture for "Open Homepage" gets recognised, but no longer sends me to my home page.
It had worked without fail before today. All other gestures I tried still work perfectly.
The Homepage in Firefox is set to "Firefox Home (Default)".

**Steps to reproduce:**
- Open any webpage in any tab
- Do the "Open Homepage" gesture ("left" in my case)
- Observe the "Open Homepage" text appear in the middle of the screen
- Release the gesture key
- Nothing happens

**My settings:**
![settings-home](https://user-images.githubusercontent.com/40686741/42079924-5c62c922-7b81-11e8-9a6f-81ec64fdca33.PNG)
![settings-general](https://user-images.githubusercontent.com/40686741/42079930-5fa8e940-7b81-11e8-94a0-8af8142bc4a6.PNG)
[exported-settings.zip](https://github.com/Robbendebiene/Gesturefy/files/2148277/exported-settings.zip)

**My System:**
- Operating system: Windows 10 Home, 64 Bit
- Firefox version: 61.0 (64-bit)
- Gesturefy version: 1.2.2

**Comment by Itchiii** [comment]
For security reasons, Mozilla has moved "about: home" to their privileged URLs.
They won't fix this "issue", because: 
> about:home should never have worked in the first place

For more information you can look on [developer.mozilla](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) or on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1468191)

**Comment by Robbendebiene** [comment]
We will provide a workaround in the upcoming major version (Gesturefy 2.0).

**Comment by Robbendebiene** [comment]
It turns out that there is no way to open the about:home tab any more :|
However for people who were using "about:home" to open their custom homepage (if it differs from about:*) the new "Open Homepage" command should work again. Other people who were using a custom URL should switch to the "Open Custom URL" command.
