### ISSUE TITLE
Feature request: Hybrid Actions

### ISSUE THREAD

**Issue by mortyobnoxious** [Robbendebiene/Gesturefy#313]
**Thank you** for this great extension.

Can you allow us to use just **ONE** "gesture" or "rocker gesture" to do all of these similar but distinguishable actions by deciding which is the case automatically:
_Link to background tab_, _Search selected text_, _Image to tab._

- **Link to background tab**: if it is a link I'm using gesture on, it will open it in a background tab.
- **Search selected text**: if it is a selected text I'm using gesture on it will search it in a background tab
- **Image to tab**: if it is an image I'm using gesture on it will open it in a background tab

If it is possible, it would be great.

Thank you again and again.

**Comment by Robbendebiene** [comment]
Thanks for your feature request.
I don't want to write an extra command for this since it's too specific, but I have 2 ideas how I could solve this:
1. I could write a custom user script for you (note that custom user scripts re not available yet, but they are on the way)
2. I could create a special command that allows you to chain other commands in a specific order. While I really like this idea, it would be quite complex to implement.

**Comment by mortyobnoxious** [comment]
Thank you, which suits you best I'm up for it.

**Comment by Robbendebiene** [comment]
We'll discuss about, for the moment I'm reopening the issue in order to keep track of it.

**Comment by kostenelo** [comment]
I also lack mega-feature of hybrid actions from FireGestures http://www.xuldev.org/firegestures/features.php
Еspecially these:
**[Hybrid] Save As.**.. (Link / Image / Frame / Page)
**[Hybrid] Copy Location** (Link / Image / Frame / Page)


> 
> 
> Thanks for your feature request.
> I don't want to write an extra command for this since it's too specific, but I have 2 ideas how I could solve this:
> 
>     1. I could write a custom user script for you (note that custom user scripts re not available yet, but they are on the way)
> 
>     2. I could create a special command that allows you to chain other commands in a specific order. While I really like this idea, it would be quite complex to implement.

**Comment by Robbendebiene** [comment]
At the moment this can only be accomplished using user scripts. The following issues rebuilds the "[Hybrid] Copy Location" as a user scripts: https://github.com/Robbendebiene/Gesturefy/issues/386

**Comment by norill** [comment]
just allow multiple actions per gesture (or multiple gestures with the same pattern). i used to have a gesture for "Back or Close" in Opera, and i managed to replicate it Mouse Gestures Suite using a script, but that was very hacky. it worked like this:
* **Navigate back**, if possible, or else
* **Close tab**
you could easily support multiple mutually-exclusive actions for the same gesture. when the actions are not mutually-exclusive (for example performing a gesture that has one action that works for images and another action for links on an image that is also a link), then the more specific actions should take precedence over less specific action. for example, if both **Navigate back** and **Close tab** are triggered, then **Close tab** is the less specific one because it has no special conditions, while **Navigate back** can only be performed if there is at least one previous entry in navigation history. in cases where both actions have some specific conditions, and both of those conditions are met (like the link-image example) then the order in which the actions were defined should decide which one would take precedence

**Comment by Robbendebiene** [comment]
@norill This is the goal of this issue. However there won't be such a thing as "specificity". The commands will be executed one after another (in the user defined order) till one succeeds. In the end this should lead to the same result as what you've described.

There is a partially working user script for your specific "hybrid action" here: https://github.com/Robbendebiene/Gesturefy/issues/69

**Comment by Robbendebiene** [comment]
This feature is now finally available in [Gesturefy 3.2.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.0) it's called [Multi Purpose command](https://github.com/Robbendebiene/Gesturefy/wiki/Multi-purpose-command)
