### ISSUE TITLE
right to left for restore tab NOT working anymore!

### ISSUE THREAD

**Issue by fuorigioco1981** [Robbendebiene/Gesturefy#317]
### Your System
- Operating system:win10
- Firefox version:61.0.1
- Gesturefy version:1.2.2

suddenly this gesture not working:righ-left for "restore tab"

**Comment by Robbendebiene** [comment]
Please provide additional information about your problem, otherwise we cannot help you.
- Does the gesture still get recognized (in other words, does the action name get displayed when you perform the gesture)?
- Is the gesture still set to left. right in the config?
- You can export your config in the add-on settings under "About" via "Backup". It would be helpfull if you could attach them here.

**Comment by fuorigioco1981** [comment]
yes action,trail is shown
action is re introduced 10 times still not working
CHANGED the .json to .jpeg because i could upload the export!
change it again to json so you see it

![gesturefy 1 2 2 tue aug 07 2018](https://user-images.githubusercontent.com/33813539/43754382-30d67424-9a13-11e8-9926-2d53dcc8229a.jpeg)

**Comment by fuorigioco1981** [comment]
tried many different action for RESTORE tab but none works!!!

**Comment by fuorigioco1981** [comment]
tell me in ffox profile which folder/file is gesturefy so i completely remove it and re install it

**Comment by fuorigioco1981** [comment]
well tried foxygestures and there also restore dont work!any idea where to search for a solution?looks like not a "pure" gesturefy problem

**Comment by fuorigioco1981** [comment]
tried developer firefox that i have  and restore works fine.so its a problem of ffox?

**Comment by fuorigioco1981** [comment]
did a reset of ffox and all ok now!thanks
