### ISSUE TITLE
Gestures Stopped Working in v2.0.1 Firefox 61.0.2

### ISSUE THREAD

**Issue by dephecked** [Robbendebiene/Gesturefy#321]
[Gesturefy_Settings.txt](https://github.com/Robbendebiene/Gesturefy/files/2278386/Gesturefy_Settings.txt)

They worked yesterday, came in this morning to the "update" screen and nothing.  I've restarted FF, backed up settings (see attached), uninstalled/reinstalled, and restored and gestures are not working.  I'm on the same version of FF as I was yesterday, literally the only thing that's changed is the Gesturefy update.  Addon is enabled.  I don't get any trails or indication that gestures are working when I right-click and drag.

- Operating system: Win 10 Enterprise v 1607, OS Build 14393.447 x64
- Firefox version: 61.0.2
- Gesturefy version: 2.0.1
- Microsoft Intellipoint Comfort Mouse 4500

**Comment by Robbendebiene** [comment]
I'm sorry for the inconvenience. Has anyone of you tried to reset the add-on settings (under options > about)?

**Comment by gfbett** [comment]
I did, same issue

**Comment by Robbendebiene** [comment]
For further debugging it would be helpful if you could open the console (ctrl + shift + J) and follow these steps:
1. clear the console (icon in the top left corner)
2. Keep the console open and reload a tab or open a new one
3. try executing a gesture
4. copy and paste the contents of the console here

**Comment by gfbett** [comment]
Error: WebExtension context not found! ExtensionParent.jsm:1014:13
TypeError: can't access dead object[Learn More] browsing-context.js:1708:1
Error: WebExtension context not found! ExtensionParent.jsm:1014:13
sendTimingEvent addSite start undefined undefined verboseLoggerHooks.js:1:1120
CSI/tbsd_ cb=gapi.loaded_0:458:127
CSI/_tbnd cb=gapi.loaded_0:458:127
TypeError: lastPoint is undefined[Learn More]
gesture-indicator.js:213:9
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;!function(){var t,e,n,o=0,u=function(t,....
widget:1
TypeError: can't access dead object[Learn More]
browsing-context.js:1708:1
sendTimingEvent addSite start undefined undefined verboseLoggerHooks.js:1:1120
[Show/hide message details.] Unchecked lastError value: Error: Could no

**Comment by Robbendebiene** [comment]
@gfbett Thank you!
I uploaded a potential fix, maybe you can try it out?
Steps to do so:

1. temporary disable your current installation of Gesturefy
2. download the zip: https://github.com/Robbendebiene/Gesturefy/archive/master.zip and unzip it
3. open "about:debugging" in Firefox and click on "load temporary add-on"
4. choose the manifest.json file in the src folder of the extracted zip file
5. try it :)

**Comment by gfbett** [comment]
yay! It does work.

**Comment by Robbendebiene** [comment]
Okay nice, I'll release another update immediately. Make sure you remove the temporary add-on and re-enable your installation :)

**Comment by dephecked** [comment]
Updated to latest and it's working now.  Thanks for the quick turnaround.  It's crazy how lost I am without the gestures.  Really increases productivity.
