### ISSUE TITLE
Feature Request: Mousewheel gesture to cycle tabs in recently used order

### ISSUE THREAD

**Issue by Ainson** [Robbendebiene/Gesturefy#335]
So basically:

- Mousewheel down is most recently used tabs in that order

- Mousewheel up is last used tabs in that order

This is how it was in Opera 12 and earlier versions, it can be tried out there, or in latest version Opera by using ctrl-tab and ctrl-shft-tab.

IMO the most intuitive way to scroll through tabs, and an incredibly useful feature. (sorely missed in Firefox)

Thanks

**Comment by Robbendebiene** [comment]
Sorry for the late reply I forgot about this issue.
This sounds like a good idea, but I'm not quite sure how it will work in practice. Because if you switch to the most recent tab the previous tab becomes the next most recent tab and so on. To solve this I need to "freeze" the last used timestamp of all other tabs at the moment of the first switch. My question is however, when do I "unfreeze" the timestamps?

**Comment by Ainson** [comment]
But switching is Ok, because as soon as you release the right mouse button to view another tab, it's fine that the one you were looking at becomes the most recent.

**Comment by Robbendebiene** [comment]
So this command would only work for wheel gestures and not for normal mouse gestures?

**Comment by Ainson** [comment]
For me that would be enough yes

**Comment by Ainson** [comment]
I see cycling through tabs in recently used order by ctrl-tab and ctrl-shft-tab is now an option in Firefox, not just in Opera.

Is it possible to link the mousewheel to these keys now?

**Comment by Ainson** [comment]
Shame as the keys emulation would work even in Firefox windows that normally don't react to any gestures, but understand if it's not possible.
