### ISSUE TITLE
Feature request: Open tab in new container gesture

### ISSUE THREAD

**Issue by gitantix** [Robbendebiene/Gesturefy#370]
I absolutely love Gesturefy. What would make it perfect is if I could use it to open new new tabs into new containers. I currently do this by using the Containers on the Go extension, but I have to do it manually. 

It would be great if Gesturefy could natively open new tabs into new containers or if I could pass a message with Gesturefy to Containers on the Go or some other extension that does the same.

Perhaps it is already possible with Containers on the Go, and I just suck at configuring Gesturefy. I manage to trigger the message passing, but nothing happens.

**Comment by Robbendebiene** [comment]
Hi, I'm glad you like Gesturefy :)
Since there already is an [issue](https://github.com/Robbendebiene/Gesturefy/issues/234) addressing this topic I'll be brief:

I couldn't find any API for "Containers on the Go". What message are you sending?

This may not be exactly what you need, but recently I found the following add-on: https://addons.mozilla.org/en/firefox/addon/temporary-containers/ To open a new temporary container cou can configure it using the "Send message to other add-on" command like so:

_Add-on ID:_ `{c607c8df-14a7-4f28-894f-29e8722976af}`
_Message:_ `{ "method": "createTabInTempContainer" }`
_Parse message:_ On
[(more information)](https://github.com/stoically/temporary-containers/wiki/Foxy-Gestures-User-Scripts)

**Comment by gitantix** [comment]
Thank you so much! This makes Gesturefy perfect!

I'm sorry I didn't find the answer to my questions before asking. You are most kind and helpful.
