### ISSUE TITLE
Feature request:  Highlight "commands" that are in use

### ISSUE THREAD

**Issue by istrasci** [Robbendebiene/Gesturefy#372]
### Describe your matter in detail
When creating/editing a gesture, when you choose the _Command_ for the gesture to execute, it would be nice to **Highlight** or _Mark_ :heavy_check_mark:  commands that are already referenced by an existing gesture.

### Your System
- Operating system: Win 10, Linux (Mint 19), macOS (Mojave)
- Firefox version:  64.0
- Gesturefy version:  2.0.4

**Comment by Robbendebiene** [comment]
Thanks for the suggestion.
However I think we may not do this for two reasons:
1. The icon or inidicator should properly explain what it indicates or what it stands for. If it does not it might rather confuse users than actually help them. It may also further clutter the UI.
2. Since binding the same command to a different gesture can be useful (for example with different command settings) it doesn't make so much sense to indicate that this command is already in use by another gesture.
