### ISSUE TITLE
"Save image" command problem - Send referer header when downloading an image

### ISSUE THREAD

**Issue by lingluo-z** [Robbendebiene/Gesturefy#393]
### Describe your matter in detail

website:  http://marvel.reactor.cc/post/3867710
there was a weird problem when i using Gesturefy to download images from the site "reactor.cc"
the image saved by gesturefy is different from which saved by "rightclick-save image as",there would be a mark added to the bottom of the image
![Gwen-Stacy-Marvel-фэндомы-Touxi-5085913](https://user-images.githubusercontent.com/50151430/56984683-2d05fe00-6bb9-11e9-8bc0-e13acdca8ac9.jpeg)
![Gwen-Stacy-Marvel-фэндомы-Touxi-5085913](https://user-images.githubusercontent.com/50151430/56984728-47d87280-6bb9-11e9-8353-367c83aa2261.jpeg)

### Your System
- Operating system: windows 10 64-bit
- Firefox version:66.0.3 (64-bit)
- Gesturefy version:2.04

**Comment by Robbendebiene** [comment]
This problem exists because the website itself adds a watermark at the bottom of the screen if you are coming from a different domain. You can try this out yourself. Just open the first result from: https://www.google.com/search?q=http%3A%2F%2Fmarvel.reactor.cc%2Fpost%2F3867710 you will notice that the little watermark at the bottom has been added to the image (because your previous site wasn't reactor.cc but google.com). If you continue browsing on this site the watermark will disappear because then your previous domain will always be reactor.cc.

**Now back to the important question, can we fix this?**
In theory it would be easy to fix this, but Firefox currently does not allow add-on developers to change this value (https://bugzilla.mozilla.org/show_bug.cgi?id=1367626). So until they do not change that, I can not do anything. Sorry.

**Comment by Robbendebiene** [comment]
Fixed in [Gesturefy 2.1.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.3)
