### ISSUE TITLE
Add other gestures

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#4]
Please add these actions:
- Open image in a new foreground tab;
- Focus on Location Bar;
- Navigate up one levels of the URL;
- Show popup history tab;

Thanks.

**Comment by Robbendebiene** [comment]
Thanks for your suggestions, just to clarify some things:
- **open image in a new foreground tab:** How do you expect this to work? Which image will open in a new tab after the gesture is done?
- **focus on location bar:** you mean something like the ctrl + l or f6 behaviour right? As far as I know firefox doesn't offer any api to do this which is sad. [(more info)](https://bugzilla.mozilla.org/show_bug.cgi?id=1295400)
- **navigate up one levels of the URL:** so you mean changing the url for example from  https://github.com/Robbendebiene/Gesturefy/issues -> https://github.com/Robbendebiene/Gesturefy and so on right?
- **Show popup history tab:** Can you clarify this? Even though I already feel it won't be possible with the current firefox api.

**Comment by happysurf** [comment]
- **Open image in a new foreground tab** > Currently with" Mouse Gestures Suite" or "Fire Gestures" is possible drag any image (I use "down" gesture) for open it in a new tab and then with "Viewhance" extension I can zoom the image.
- **focus on location bar** > Yes, thanks for the sad info.
- **navigate up one levels of the URL** > Exactly.
- **Show popup history tab** > This is the pupup for see the history tab:
![history](https://cloud.githubusercontent.com/assets/13637587/26754369/0ee1ea06-487a-11e7-8506-5db139f45745.png)

**Comment by Robbendebiene** [comment]
Alright, so for the moment I will add "navigate up one levels of the URL" and I would add the possibility to open any image or link where the gesture started in a new tab. In this case you wouldn't drag the image. What do you think about that? Maybe there are other things that could be opened in a new tab besides links and images?

The last one "Show popup history tab" isn't that likely to be implemented. Because there are 2 main problems. First I can't create such a classic popup/context menu, I can only add items to the normal one, however I could display it with standard HTML. Second I'm not sure if I can get the history related to a specific tab without tracking it on my own.

**Comment by happysurf** [comment]
In addition to the images and links will be great open in a new tab also a **text selection search.**

For the second gestures, a small HTML history panel for **the active tab** is a good idea, if this is possible.

**Comment by Robbendebiene** [comment]
**"navigate up one levels of the URL"** is now implemented (commit: cd51e5cddcee0f3df218bd51454a085b91486577) and will be available with version 1.0.2 quite soon.
 
I'm looking into **"open image in a new foreground tab"** and I really like the idea of a text selection search, but unfortunately it's currently impossible, because I can't get the users default search engine. Nevertheless it sounds like it will be possible in the future.
see here:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1352598
- https://bugzilla.mozilla.org/show_bug.cgi?id=1268401

**Comment by happysurf** [comment]
Thank you for detailed info on development.
**About the text selection search,** will be good use Google at moment because this is better that nothing. :-)

**Comment by Robbendebiene** [comment]
I'm still struggling with the question whether or not it's better to have 3 or 2 separated gestures for these actions (open link, open image, search text) or only one. Because one gesture could nearly cover all these actions since they depend on the target where the gesture started (link or image) and if there is any text selected or not. The only question is, what action will be executed if I start over an image or link while text is marked. So maybe splitting it up into 2 gestures would be the best? one for opening images and links in a new tab and the other for performing a search?

**Comment by happysurf** [comment]
Maybe I don't understand, but in other old extensions like Fire Gestures or Gesture Suite all the gestures are separated because each action require a different script code, for that I think is better for the user have the possibility of choose what action they want.

**Comment by happysurf** [comment]
Sorry I have closed the issue but is a mistake.
Please re open. :-)

**Comment by stmr** [comment]
I love the idea of gesture that opens links and images, to combine them just sounds smart, I would love them to open background tabs however (or just have one for foreground and one for background).
The search selected text needs a separate gesture :)
I hope it will be possible to do the Open this (link/image) in background, the javascript function that FireGestures use was blocked in Nightly I think on the 5th of June

**Comment by Robbendebiene** [comment]
> what would happen if there's a ling over an image? (e.g. facebook)

It depends on the html, css styles and how I'm going to implement it. Because of that I think splitting it up is the best solution so far, even if I would like to combine them.

> Also a gesture for saving image at the starting point of a gesture would be awesome.

With saving you mean downloading the image? I already thought about such things, like saving the current page, but I didn't found a trivial solution yet.

Some further questions:
- should the "open image gesture in new tab" also work for elements which have a background image or only for normal images?
- even if I could easily implement always two gestures one for opening in the foreground and and one for background it feels a bit messy, wherefore I would implement only one version (at least for now). I plan to open images and links in the background but text selection search in the foreground. What do you think?

**Comment by happysurf** [comment]
> should the "open image gesture in new tab" also work for elements which have a background image or only for normal images?

For all elements that permit to view the image, like the user icons of this thread.

> even if I could easily implement always two gestures one for opening in the foreground and and one for background it feels a bit messy, wherefore I would implement only one version (at least for now). I plan to open images and links in the background but text selection search in the foreground. What do you think?

I never understand the sense of "open a tab in background" because if I decide to do an operation like open a link or an image I want see the result right now not after 15 minutes.
I think that "open in background" is much less used and useful in my opinion.
Please open all gesture actions in foreground (default) and in background as option.

**Comment by Robbendebiene** [comment]
> I never understand the sense of "open a tab in background" because if I decide to do an operation like open a link or an image I want see the result right now not after 15 minutes.

I totally agree with you, but @stmr seems to think the opposite way and I have to admit, that sometimes I'm opening multiple links in a new tab from one page (using middle mouse button), wherefore opening in the foreground would be really annoying.

So for opening a link I would provide both possibilities, but I guess for images it's enough to only open them in the foreground, likewise the selection search. Maybe @stmr can state his opinion on this? 

> Meanwhile I remembered another interesting gesture to be implemented if possible (but I don't think);
> Open > "View Page Info" window, very useful for set in the Permission section many parameters like the cookies behavior.

Yep, would be nice, but it's impossible with the current API.

**Comment by stmr** [comment]
I never really understood opening in new tab in foreground, you can just click the link and then use back button to get back :) (I understand some reasons of course, I was just trying to be funny)
I'm definitely voting for opening in background for at least the links (possibly for images in the future, I don't use that one that much).
For searching, foreground is the way to go.

**Comment by Robbendebiene** [comment]
Alright, thanks to both of you. I plan to submit version 1.0.2 tomorrow to mozilla.

**Comment by stmr** [comment]
Thanks a lot! You're amazing

**Comment by happysurf** [comment]
I can't wait. :-)
Thanks.

**Comment by Robbendebiene** [comment]
I'm closing this. For new ideas and feature requests please open a new issue.
