### ISSUE TITLE
New private window not working

### ISSUE THREAD

**Issue by bsc11** [Robbendebiene/Gesturefy#411]
### Describe your matter in detail

When I use the open new private window gesture, nothing happens. Everything is normal if I try to open a non-private window

### Your System
- Operating system: Windows 10 x64
- Firefox version: 68
- Gesturefy version: 2.1.1

**Comment by Robbendebiene** [comment]
Hi, it's working for me. Can you please post the console log here after performing the gesture?
In order to get the console log please follow the steps below:
1. Open console via ctrl + shift + j 
2. clear the console (icon top left)
3. Perform the gesture on any website
4. Go back to the console and copy any logs here (or screenshot it)

Your configuration would be helpful too. You can export it in the Gesturefy settings in the "About" section.

**Comment by bsc11** [comment]
I figured it out--had the Firefox "Run in Private Windows" option set to the wrong one. Thanks!

**Comment by Robbendebiene** [comment]
Ah interesting, thanks for the information. I'm closing this issue then.
