### ISSUE TITLE
[Feature request] Super drag (hyper drag)

### ISSUE THREAD

**Issue by Dreamer8** [Robbendebiene/Gesturefy#432]
Hello, I like Gesturefy, thanks for creating it, but I miss one important feature:

**Super drag** (or hyper drag) - options to do actions when I drag the link/image/selected text up/down/left/right.

It's useful to open multiple links in background tabs, or quickly open link in a new tab.

Currently I'm using [Hyper Drag](https://addons.mozilla.org/en-US/firefox/addon/hyper-drag/) extension, but it would be better to have it all within one extension - and I think it would be useful also for Gesturefy users.

Thanks.

**Comment by Robbendebiene** [comment]
Hi thanks for your feature request. However there already exists an [issue for this kind of feature](https://github.com/Robbendebiene/Gesturefy/issues/200).

There are two main reason because it's not implemented yet.

1. I still have no concept of how to properly integrate this feature in Gesturefys current settings UI.
2. [Hybrid Gestures](https://github.com/Robbendebiene/Gesturefy/issues/313) are far more powerful and nearly cover all of the drag gestures use cases.

**Comment by Dreamer8** [comment]
Thanks for the reply, no problem, Gesturefy works good with Hyper Drag extension, no conflicts, but I'm not using all features.

**Comment by Robbendebiene** [comment]
Appreciate your understanding!
I'm closing this issue then as a duplicate. If you have any further ideas about this feature please post them here: https://github.com/Robbendebiene/Gesturefy/issues/200
