### ISSUE TITLE
Left mouse button. which triggers a gesture.

### ISSUE THREAD

**Issue by Gunderyk** [Robbendebiene/Gesturefy#452]
Windows 8,1, Firefox,  Gesturefy, Version: 2.1.6
I mean Settings, Mouse Gesture Button, Mouse Button that Makes a Gesture. When I switch from the right to the left button, almost everything is ok. However, there is a problem because the left mouse button cannot select text on pages. :) Of course, you can set the right button, but it's much easier to use the left mouse button because I'm an invalid. If this error could be corrected, I would be very grateful.

**Comment by Robbendebiene** [comment]
Hi, this problem lies in the behavior of text selection. When setting the gesture mouse button to the left mouse button, selecting text and making a gesture consist of the same interaction: 1. left mouse button down 2. moving your mouse 3. releasing the left mouse button. To explain this better try to put yourself in the program/add-ons perspective:
When your left mouse button goes down you might select some text, you might start a gesture or you even might start dragging an image or something similar. The program does not know which of these actions you want to accomplish. Even the text cursor is no indicator for the start of a text selection, since you can start a text selection on an empty space.

The left muse button for gestures only makes sense in conjunction with a suppression key (you can set in the Gesturefy option page). So you always have to press the specified suppression key in order to select something.

**Comment by Gunderyk** [comment]
Thank you very much for your clarification. I set the damping gesture and everything is as it should be, although it is a bit of a pain. For example, Kinza browser, Cent Browser is something like this: - Turn on super drag, Super Drag is a function that opens the search results page by selecting text and dragging and dropping. A solution that's okay. Each browser is different, has its pros and cons.

**Comment by Robbendebiene** [comment]
> I set the gesture of suppression and everything is as it should, although it is a bit of a pain.

I understand that, I neither think that this is a good solution.

> For example, Kinza Browser, Cent Browser has this option: - Enable Super Drag, Super Drag is a function that opens the search results page by selecting text and dragging and dropping. A solution that's fine. Would it be possible for you to do this function in Gesturefy? This is really a great solution.

Maybe I'm misunderstanding you, but wouldn't this only solve your problem for very specific gestures like the "Search selected text" one?

The feature itself has already  been requested here: https://github.com/Robbendebiene/Gesturefy/issues/200 but I did not had the time to implement it.

**Comment by Gunderyk** [comment]
First of all, I'm sorry for the trouble. I understand that you don't have time, but will you do this function in the future when you have time? I would ask you so much on my behalf and for sure many other users.
Maybe I'm misunderstanding you, but wouldn't this only solve your problem for very specific gestures like the "Search selected text" one?
Yes you are right. Especially in my case it is useful because I am an invalid. In addition, it is more convenient for everyone to press the left button than the right one.

**Comment by Robbendebiene** [comment]
I have nothing against this feature and am aware of its advantages, but I currently don't know how to properly integrate it into Gesturefy, especially in the user interface / settings page.

**Comment by Gunderyk** [comment]
I would like to advise you, but I am a layman in this matter, so I do not speak. One thing I know, it would certainly be a great help for many Invalids. Please try, maybe model on CentBrowser, sorry, maybe it's bad advice. :)

**Comment by Robbendebiene** [comment]
I've looked into the Cent Browser UI and it takes a very different approach than Gesturefy does.

Since the topic of this issue is now about drag gestures I'm closing this issue in favor of #200. If you have any ideas or suggestions for drag gestures please post them there :)

In case you have another idea how to solve your original problem and improve Gesturefy for disabled people feel free to reopen this issue or open a new one.

**Comment by Gunderyk** [comment]
Tell me please, are you planning in the future and is there any chance, a technical possibility that you will join Super Drag with your Gesturefy extension?


24 marca 2020 


I've looked into the Cent Browser UI and it takes a very different approach than Gesturefy does.
Since the topic of this issue is now about drag gestures I'm closing this issue in favor of #200. If you have any ideas or suggestions for drag gestures please post them there :)
In case you have another idea how to solve your original problem and improve Gesturefy for disabled people feel free to reopen this issue or open a new one.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



