### ISSUE TITLE
[Feature Request] Make settings of commands easier to find

### ISSUE THREAD

**Issue by RheingoldRiver** [Robbendebiene/Gesturefy#453]
I have two Reload tab gestures, one is a normal reload, the other is cache reload. From here they are identical, which is fine because I could just name them differently if I wanted:
![image](https://user-images.githubusercontent.com/18037011/78021482-efee4280-7318-11ea-94a5-1a1d88d30d53.png)

But here, they are also exactly identical:

![image](https://user-images.githubusercontent.com/18037011/78021511-fb416e00-7318-11ea-8fdf-33cede07d711.png)

I think from this screen, it should show at least a link to edit settings, with the number of non-default values set, or (preferably) allow the left pane to scroll and settings to be edited from here. Just now it took me about 5 minutes to discover how to verify that the settings were in fact how I wanted them because I couldn't find the place to edit settings - there's no indicator here even that this can be clicked, except for the info icon, which is the only place you *can't* click:

![image](https://user-images.githubusercontent.com/18037011/78021843-89b5ef80-7319-11ea-9740-99154cf317ac.png)

In the end, this is only a small QOL issue, though, I love this extension & it's been an integral part of my workflow for years and years, thank you!

**Comment by Robbendebiene** [comment]
We have been struggling with this problem for a while, but haven't found a good solution yet.

We thought about changing the indicator of the command selection field to a gear icon or something similar, if the command offers special settings. This gear icon could also be clickable to immediately open the command settings.

![grafik](https://user-images.githubusercontent.com/13716661/78237900-3a6bec80-74dc-11ea-8e4e-09dcc013323e.png)

The reason we disliked the idea, is that we lose the indicator for the command field / command sidebar.

>  allow the left pane to scroll and settings to be edited from here.

While this seems like an obvious solution, it won't work for wheel and rocker gestures, since they do not require this popup.

>  there's no indicator here even that this can be clicked, except for the info icon, which is the only place you can't click:

Theoretically we cannot simply replace the info indicator with a gear icon since we already replace it with a key icon to indicate extra permissions. Otherwise this would lead to a problem if a command has additional settings and requires additional permissions.

When I think about it, dropping the permissions indicator for a settings indicator might actually be better, because additional settings are probably more interesting to the user than additional permissions.

It would be great to get some other ideas or mock ups here which we can evaluate.

**Comment by RheingoldRiver** [comment]
Ah, this all makes sense, thanks for the writeup!

What about prepending a * before actions that have more settings, and then below the text "Command bar" at the top of the pane, write, "Commands indicated with * have additional settings available on click"?

**Comment by Robbendebiene** [comment]
> What about prepending a * before actions that have more settings, and then below the text "Command bar" at the top of the pane, write, "Commands indicated with * have additional settings available on click"?

Good suggestion, this would also be easy to implement.
However I'm personally not a big fan of explaining things to the user. The UI should explain itself.

**Comment by RheingoldRiver** [comment]
>  However I'm personally not a big fan of explaining things to the user. The UI should explain itself.

Yeah I do agree with this, maybe for now do this but keep the issue open for a better fix later?

**Comment by Robbendebiene** [comment]
With the release of Gesturefy version [3.0.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.5) commands with additional settings now have a gear icon as an indicator, while the permissions indicator is only visible in the additional info section, which appears when hovering over the command for a short time.
