### ISSUE TITLE
[Feature Request] Adding gmail gestures (next and previous email)

### ISSUE THREAD

**Issue by kolfers** [Robbendebiene/Gesturefy#466]
### Describe your matter in detail
I have a suggestion to add some functionality to Gmail. I just switched to Firefox from Chrome, where I was using "Gmail Mouse Gestures", to quickly go through my inbox with swipes.  The following scripts can be used to go forward and backward through mails in the inbox:

To older email:
document.getElementsByClassName('adg')[1].click()

To newer email:
document.getElementsByClassName('adg')[0].click()

I understand that this is easy to do (**if ** you are even aware of this functionality, and **if** you know / can find these lines) by activating the user script, which I can confirm the work btw. But for people not familiar with that option, adding two buttons in the Command Bar could help a lot I think. 
Thanks!
### Your System
- Windows 10
- Firefox version: 74.0
- Gesturefy version: 2.1.6

**Comment by Robbendebiene** [comment]
Thanks for your suggestion.
However this is way too specific for a predefined command, because it only targets a specific website. User scripts are meant to be used for these kind of things.

So I'm sorry, but I cannot add every possible command. Otherwise Gesturefy would be cluttered up with more commands than it already is.
