### ISSUE TITLE
Feature Request: Adding Up, Down, Left, Right arrow keys as commands

### ISSUE THREAD

**Issue by jacoalda** [Robbendebiene/Gesturefy#467]
Hi, thanks for this add-on, its the only one that seems to work with my 2-in-1 touchscreen laptop when in tablet mode.

I am requesting these keyboard arrow keys because I primarily use my laptop in tablet mode and for certain sites like Viz when reading manga or Twitch when watching vods, I can't seek the content unless I open up the touchscreen keyboard each time which obstructs the screen.

Adding these 4 arrow keys would solve those problems because I could map the left arrow key using left gesture to change a manga page on Viz or even other manga sites and same with right (up and down arrow keys would be used for navigating the manga vertically if zoomed in but are not needed), and on Twitch it would make it easier to seek videos 5sec forwards or backwards. 

Please, and I hope this problem is not too niche?

**Comment by Robbendebiene** [comment]
Hey, thanks for your feature request.
Unfortunately Gesturefy or add-ons in general cannot properly mimic keyboard keys.

However there are two options.
1. Try to mimic the event with one of the following code snippets.
In order to test these code snippets, go to your specific website and open the console by pressing ctrl + shift + K. Then paste the code snippet in the console and execute it.
If none of these work, than the website does an extra check if the keyboard events are from a real keyboard or if they are generated.
Note: if they don't work try replacing the "keydown" string with "keyup" or "keypress"

Mimic right:
`window.dispatchEvent(new KeyboardEvent("keydown", { key: 'ArrowRight', code: 'ArrowRight', keyCode: 39, which: 39 }));`

Mimic left:
`window.dispatchEvent(new KeyboardEvent("keydown", { key: 'ArrowLeft', code: 'ArrowLeft', keyCode: 37, which: 37 }));`

Mimic down:
`window.dispatchEvent(new KeyboardEvent("keydown", { key: 'ArrowDown', code: 'ArrowDown', keyCode: 40, which: 40 }));`

Mimic up:
`window.dispatchEvent(new KeyboardEvent("keydown", { key: 'ArrowUp', code: 'ArrowUp', keyCode: 38, which: 38 }));`



If one of these code snippets works, then you can use it as a script in the User Script command.

2. If option one doesn't work we can certainly trigger the "page change" in some other way. But for this I would have to examine the websites a little bit.

**Comment by jacoalda** [comment]
Unfortunately, these don't work, tried keyup and keypress for the 4 directions as well.

But lol, I figured it out somehow by putting parts of ur code in google, and after going through and trying severaI stack pages I eventually found this: 
https://gist.github.com/sukima/9822950

And used richard's referenced answer:

keyPress(37);

Originally thought I needed all the other code but didn't at all, and just used ur keycodes changed the 37 to 39 for right, 38 for up and 40 for down in case anyone else have same problem, anyways thanks!

**Comment by Robbendebiene** [comment]
Thanks for your update.

So the following code works for you:

```
function keyPress(key) {
  var event = document.createEvent('Event');
  event.keyCode = key;
  event.key = key;
  event.initEvent('keydown');
  document.dispatchEvent(event);
}

keyPress(37)
```

The reason why my code is not working is probably because I'm using the window as the target element on which I dispatch the events. If you change `window` to `document` it might work as well. Like so:

```
document.dispatchEvent(new KeyboardEvent("keydown", { key: 'ArrowRight', code: 'ArrowRight', keyCode: 39, which: 39 }));
```

**Comment by jacoalda** [comment]
Yea weird, the 'document.' change makes it work on Youtube but not viz or Twitch so I'll stick to the long code

**Comment by Robbendebiene** [comment]
All right. So I'm closing this issue.
