### ISSUE TITLE
Action for "open most recently closed tab"

### ISSUE THREAD

**Issue by blixtor** [Robbendebiene/Gesturefy#470]
I'm aware there is an action that opens a popup menu of the most recently closed tabs.

However, I'm looking for an even quicker way back after the "oops, closed the wrong tab" moment. Basically the Undo operation for the "close tab" action.

This was available in FireGestures and I found it very helpful and intuitive, as one can put "close tab" and "open most recently closed tab" on mirrored gestures (like up and down).

**Comment by Robbendebiene** [comment]
There already exists a command for this. It's called "Restore tab" and can be found right at the top of the command bar. 

> This was available in FireGestures and I found it very helpful and intuitive, as one can put "close tab" and "open most recently closed tab" on mirrored gestures (like up and down).

This is exactly the way I'm using it and it was always set as a default gesture until version 3.0. Now it's no longer set as a default gesture since it requires the additional "sessions" permissions.

**Comment by blixtor** [comment]
Ahh, great, thank you!

I overlooked this, searching for "recently", "closed" and "tab", where the last search term shows a lot of results, including the one I needed.

This issue can be closed.
