### ISSUE TITLE
Previous / Next Page (Auto-Detect Link)

### ISSUE THREAD

**Issue by weorsi** [Robbendebiene/Gesturefy#502]
This is a script gesture of Firegestures, can you add this?
I hope there can be two actions in one gesture, for example:
"→" If "History forward" is not available, execute "Next Page (Auto-Detect Link)"
"←" If History Back is not available, execute "Previous (Auto-Detect Link)".
And let users add prev next keywords.

**Comment by Robbendebiene** [comment]
There already exists a user script for the  "Next Page (Auto-Detect Link)" part: https://github.com/Robbendebiene/Gesturefy/issues/277

"History Next" is simply: `window.history.forward();` The problem is detecting if the browser can go forwards. There doesn't exist a good solution for this yet, but some workarounds have been posted here: https://stackoverflow.com/questions/3588315/how-to-check-if-the-user-can-go-back-in-browser-history-or-not

So you could pick a workaround and combine it with the other user script.
