### ISSUE TITLE
New tab is empty

### ISSUE THREAD

**Issue by thany** [Robbendebiene/Gesturefy#51]
The new tab gesture opens a new tab... And then, nothing.
A new tab in my config should display [speed dial](http://speeddial.uworks.net/), just like what happens when I do Ctrl+T.

It doesn't even display the useless "firefox start page" (the one with the giant firefox logo and google search bar). The new tab, as executed from this addon, is *completely* empty.

**Comment by Robbendebiene** [comment]
What happens if you type "about:newtab" in the url bar? Do you see an empty tab or your special page provided by "speed dial"? If you see an empty tab, then this problem should be adressed by speed dial, because it'snot setting the new tab page correctly (more info: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides) For example it's working fine with this addon: https://addons.mozilla.org/de/firefox/addon/new-tab-override/

**Comment by thany** [comment]
Well, that addon won't work as of Firefox 57 anyway. But the point of the matter is that new tab should do whatever Ctrl+T does. It's not neccesarily specific to my speed dial addon - it could in theory be anything.

**Comment by Robbendebiene** [comment]
It does the same thing as Ctrl + T.
