### ISSUE TITLE
Gesturefy on Firefox 78.0.1

### ISSUE THREAD

**Issue by kormitigrov** [Robbendebiene/Gesturefy#513]
Gesturefy stopped working after Firefox updates to 78.0.1 on Windows 10. Does not react on the gestures I used before. I am also unable to define any gestures at all. The window which prompts to enter a new gesture with the right mouse button does not react at all on this mouse button.

![изображение](https://user-images.githubusercontent.com/11956787/86430242-3afa6600-bd0b-11ea-81cc-cee67b4db037.png)

**Comment by Robbendebiene** [comment]
Are you using Firefox Sync? If so then there probably is a conflict issue with an older config from another device.
You can export your config and post the file here, I might be able to restore it or you just reset Gesturefy (both of these functionalities can be found in the About section).

**Comment by kormitigrov** [comment]
Yes, indeed! A very shrewd guess! I am using a firefox sync with another device with firefox 77. What do you propose I should do? Update another device to the same version to avoid conflicts in the future? Or reset Gesterfy on a malfunctioning firefox?

**Comment by Robbendebiene** [comment]
If Gesturefy is still working on your other device you can update it on the other device to version 3.0.x (about:addons > gear icon top right). If the update succeeds you can than either force Firefox sync to sync your settings or (probably the better way) export your config and import it into Gesturefy that is running in Firefox 78 on the other device. Note that after the update to version 3 you might have to adjust some of your gestures or alternatively change the "Matching algorithm" in the settings to shape independent.

You cannot use Firefox sync and 2 different major versions (version 2 and version 3) of Gesturefy because the configs are not compatible. So you'll have to decide to either disable Sync for add-ons or to use the same Gesturefy version.

**Comment by kormitigrov** [comment]
My config is not an issue altogether, I can configure everything I need in a minute. The problem is the Gesturefy works on FF 77 fine and does not allow me to enter any gestures on FF 78.

**Comment by Robbendebiene** [comment]
So you are using Gesturefy version 3 on both of your systems?

**Comment by kormitigrov** [comment]
Just checked: 2.0.3 on FF 77 and 3.0.4 on FF78. I got your point, it is the Sync which causes the problem, but the addon just can not detect and warn the user of the situation. Thank you for the clarification, hope it is all back to nornal if I update both machines. If somehow it is not, I'll report back.
