### ISSUE TITLE
Boycott Features Extensions programme

### ISSUE THREAD

**Issue by zakius** [Robbendebiene/Gesturefy#518]
Imagine the audacity to *feature* extension that just can't work properly due to your own shortcomings

I suggest you to automate sending salty mails to their support till they fix their API

**Comment by Robbendebiene** [comment]
Sorry, I'm not sure if I understand the point of this issue.

If it is about the limitations of the webextensions API, then sending spam mails is most certainly not a solution for me.

**Comment by zakius** [comment]
if nothing else works you should just tell them you refuse to be part of the programme until they fix their API and remind them of that on every occasion, they got lost in their own reality and completely lost contact with our world

obviously it's your decision but I'm sure you already tried everything else to make them cooperate and you still can't have your tool work as it should due to their bad decisions

**Comment by Robbendebiene** [comment]
To give a short statement of mine on Mozilla and their webextension API:

I also often feel disappointed about the development and the direction the webextension API is gooing.
Mainly because the API comes with many restrictions and even more were introduced during the years. For example the restriction to access pdfs displayed directly inside the browser, or the recently added limitation to the sync storage API (I also asked them for the reason behind this and to me it seemed like chrome parity was the main reason). Also some very crucial bugs didn't got fixed after years.

On the other hand I also know most of the reasons for this. For example the focus on designing a simple, compatible and secure high level API, or simply the lack of time and overwhelming feature requests. They are also heavily working on a Project called Fission (which will lead to some code rewrite for Gesturefy again). This is a project that affects many parts of Firefox and therefore also consumes the time of the webextension API developers.
I also know from my own experience that there are always people that prioritize differently from one self and there also have been several good API additions and bug fixes which often get overlooked.

At the end of the day, Firefox is open source which means you can always contribute the missing code yourself, but most importantly it is free and complaining about something that didn't cost anything always felt wrong to me (it can be criticized nonetheless).

My hope is that maybe next year we will see some improvements again.

**Comment by zakius** [comment]
limited doesn't equal secure
and once again, this extension suffers greatly due to these limitations so it's plainly stupid of them to *feature it* but not improve the API to make it actually work as intended (even though you clearly state in their own repository it's their fault they seem to be happy with it...)

I had hope when 57 hit alpha, I had hope when first quantum ESR surfaced, but now we clearly see every new release removes or breaks another thing and it's simply sad
