### ISSUE TITLE
"Paste and Go" --> GESTURE

### ISSUE THREAD

**Issue by kramola-RU** [Robbendebiene/Gesturefy#523]
Now I`m using two separate gestures for 1)googling and 2)openURL from clipboard.
But latest builds of FF is capable of smartly handling the "Paste and Go" command.

Could you add to Gesturefy one more gesture: **"Paste and Go"** ?

**Comment by Robbendebiene** [comment]
Could you please elaborate further on what "paste and go" means, or even better give an example how it should work? Add-ons cannot paste things inside the URL bar and thus cannot make use of its functionality. Add-ons can either start a search or open an URL. There is a command called "search from clipboard", but I guess this is not what you want?

**Comment by kramola-RU** [comment]
> Add-ons cannot paste things inside the URL bar and thus cannot make use of its functionality.

wow how bad!  :(
I need exactly this functionality.

Is that impossible even via user script?

**Comment by kramola-RU** [comment]
I can`t understand...
The Gesturefy can recognize the contents of the clipboard.
Why the Gesturefy can't perform two different actions per one gesture depending on the contents of the clipboard?
When I perform the gesture (for example gesture "--->"), I want to:
**1**) If the clipboard contains plain text, then a Google search must be performed.
**2**) If the clipboard contains a URL, then just open the page in a new tab.
Why Gesturefy can't do it?

**Comment by Robbendebiene** [comment]
@kramola-RU Gesturefy can do this. I just said, that it cannot make use of the native behaviour of the address bar which can also switch tabs, open bookmarks or search with different search engines etc.

Since this command would be a combination of "Open clipboard URL" and "Search clipboard", chaining commands would solve your problem. This is tracked here: https://github.com/Robbendebiene/Gesturefy/issues/313

> Is that impossible even via user script?

User scripts sadly cannot access the clipboard.

**Comment by kramola-RU** [comment]
> This is tracked here: #313
> chaining commands would solve your problem

How can I do this in the Gesturefy settings?
How to do the "chaining commands"?

**Comment by Robbendebiene** [comment]
It's not possible yet.

**Comment by kramola-RU** [comment]
Clear :)

**Comment by kramola-RU** [comment]
The Gesturefy is unable to recognize the phrases like **github.com** as an URL and therefore the "Open clipboard URL" does not work.
Could you to fix that ?

**Comment by Robbendebiene** [comment]
> The Gesturefy is unable to recognize the phrases like github.com as an URL and therefore the "Open clipboard URL" does not work.

Can you please open a new issue for that?

> How to do the "chaining commands"?

Since https://github.com/Robbendebiene/Gesturefy/issues/313 will be the next big thing I'm working on, I would like to close this issue because it will be solved when the other issue is solved (you can follow https://github.com/Robbendebiene/Gesturefy/issues/313 for updates).

**Comment by Robbendebiene** [comment]
All right I'm closing this as a dependency of #313
