### ISSUE TITLE
Allow %s (placeholder) in search commands

### ISSUE THREAD

**Issue by DasRentier** [Robbendebiene/Gesturefy#537]
I would like to show you my searchtools that I love and can't go without any more.

As you type e.g. "p sweet cat" into your address bar you get pictures of sweet cats.
Or "a puzzle" you get to the amazon puzzle search
Or "t una palabra" you get the translation of the spanish word palabra at deepl.com

My idea is to also implement it into Gesturefy.

So
You just have to bookmark your favourite search engine or favourite service and define a keyword in the last line of the bookmark's setting.

Then put "%s" where you want your future "XYZ"-search or -translation or -pictures or -videos. You'll get it in a minute and it's worth it. Stay with me.

Then whenever you type
"[shortcut] spacebar XYZ", you will have your comands fulfilles like you had a djinn.

Search cheese cake with Duckduckgo (last year, safe search off, worldwideweb) gets you:
     https://duckduckgo.com/?q=cheese+cake&t=h_&df=y&ia=web

With "%s" you have a placeholder for what comes next.
     https://duckduckgo.com/?q=%s&t=h_&df=y&ia=web
So you can go 
     https://duckduckgo.com/?q=%s&t=h_&df=y&ia=web cheese cake
and will end up with the link obove.
(At least it works with bookmarks and it it what you want and this is just to get the idea)

Often times you can move the elements around, but not always that easy:
https://duckduckgo.com/?ia=web&&t=h_&df=y&q=%s

So this way I use the Gesturefy search for anything that you can add at the end.
I just leave it like
https://duckduckgo.com/?ia=web&&t=h_&df=y&q=

This is already very nice but it could be ever cooler: So I have a
WISH: 
  - Can you make it work that anything I marked (or have in the cache) can go as %s or GESTY also?

SUGGESTION: 
  - Use the following and more as suggestions and useable links in Gesturefy already as presets, so not everyone has to program it him/herself

[Edit1: So what I do in Gesturefy is to mark some text and draw a p with the right mouse to search images of it, or draw a t to translate the text or draw an n to read the latest news about it...]

More examples from my bookmarks:
(I would be happy if you had even more ideas)

image search:
  https://duckduckgo.com/?t=ffab&iar=images&iax=images&ia=images&q=%s
[Edit1:This link without %s inside Gesturefy's search gives me images of the marked text quicker than the standard search with adjustments like no safe search or language...]

translation with deepl:
  https://www.deepl.com/translator#en/de/%s

or google:
  https://translate.google.com/?hl=de&tab=TT#view=home&op=translate&sl=en&tl=de&text=%s

or leo:
  https://dict.leo.org/?lp=ende&from=fx3&search=%s

I'm feeling lucky
(redirect to the first result to your search),
I use "1" as keyword and love it as I use it 50 times a day:
  https://duckduckgo.com/?kp=-2&kz=1&k1=-1&q=!ducky+%s
So if I type "1 fqcebok" i directly get to https://www.facebook.com, because it was duckduckgo's first result.

I'm feeling lucky with google (don't use google, as they don't use their slogan "don't be evil" any more, they are evil!) 
  https://www.google.com/search?btnI=1&q=%s

YouTube:
https://www.youtube.com/results?search_query=%s

YouTube 1st result:
http://www.google.com/search?q=%s+site%3Ayoutube.com&btnI=Im+Feeling+Lucky

Wikipedia:
https://en.wiktionary.org/w/index.php?search=%s&title=Special%3ASearch&go=Go&ns0=1

Amazon:
https://www.amazon.com/s?k=%s

ebay:
http://www.ebay.com/sch/%s

Twitter:
https://twitter.com/search?q=%s

ebay Germany:
http://www.ebay.de/sch/%s

Amazon Germany:
https://www.amazon.de/s?k=%s

Amazon fake review checker, use product number after space:
https://reviewmeta.com/amazon/%s

Amazon fake review checker german, use product number:
https://reviewmeta.com/de/amazon-de/%s

German wikipedia:
https://de.wikipedia.org/wiki/Spezial:Suche?search=%s

Duckduckgo German +:
https://duckduckgo.com/?kl=de-de&kp=-2&kz=1&k1=-1&q=%s

Then if i have stored d for my duckduckgo+ search, I just type
"d how to be extra cool"
--> https://duckduckgo.com/?t=ffab&df=y&ia=web&q=how+to+be+extra+cool

or translate with t
"t constitution"
--> https://www.deepl.com/translator#en/de/constitution

Well, maybe you can just use these examples and embed in into your beautiful Gesturefy. It is so great and will become even greater with or without me.

Hope, my idea finds its way into the Add-On or could at least make someone's life easier.

cu and have a beautiful day

[Edit2: Is it possible to just have some 
   - keyboard text with an enter at the end or something like 
   - "ctrl" + "-" or 
   - "ctrl" + "p" or 
   - the individually chosen shortcut to another add-on?]

**Comment by Robbendebiene** [comment]
Congratulations. You are the new "make the most detailed issue" leader. :D
You've got some really interesting use cases for one single command too. 

Still I'm not exactly sure if I got what you are asking for.
At first I thought you want the "Search text selection" command to use %s as a placeholder for the selected text instead of just appending the selected text to the end of the URL.

> Well, maybe you can just use these examples and embed in into your beautiful Gesturefy. It is so great and will become even greater with or without me.

This however sounds like you want your examples as predefined/standard gestures in Gesturefy?

> [Edit2: Is it possible to just have some
> 
>     keyboard text with an enter at the end or something like
>     "ctrl" + "-" or
>     "ctrl" + "p" or
>     the individually chosen shortcut to another add-on?]

And there you've lost me. It sounds like a totally different feature request.

So can you please elaborate more on your actual request?

**Comment by DasRentier** [comment]
Hey Robbendebiene,
I'm sorry I didn'd answer, I just came back from my electronic-free vacation.

Yes, I have mixed up different ideas, but they belong together as one thought-block.

> At first I thought you want the "Search text selection" command to use %s as a placeholder for the selected text instead of just appending the selected text to the end of the URL.
--> Correct

> >     Well, maybe you can just use these examples and embed in into your beautiful Gesturefy. It is so great and will become even greater with or without me.
> This however sounds like you want your examples as predefined/standard gestures in Gesturefy?
--> Also Correct. You are offering so great examples, so why not just offering 100 as it took me some time to figure out intuitive gestures. And there are better ones than mine for sure.

The Edit2 is not understandable, I don't drink, but it sounds like I have. Sorry.
I meant a new Gesturefy-order to insert simple _predefined text_ or _code_ or a _keyboard-shortcut_.
I do a gesture and it pastes a saved text like:
"Dear Sir or Madam" or

"Address, Streetname, City, Telephone, email" or

" *!DOCTYPE html>
*html>
*body>
*h1>My First Heading/h1>
*p>My first paragraph./p>
*/body>
*/html>"  [*<]  or

the print-command "[ctrl-key]+p" or

predifined text and [enter-key] 

Some other commands or Add-ons work with keyboard-shortcuts like [ctrl]+[alt]+[any-key], but I think you have already written elsewhere, that it isn't possible. 



I hope you find my ideas useful of any kind. Thank you for your great add-on. 

Have a nice day


![gesten](https://user-images.githubusercontent.com/45996677/93667517-d2f42a00-fa86-11ea-9361-186a32c1c5d6.jpg)

**Comment by Robbendebiene** [comment]
Hi @DasRentier 

> I'm sorry I didn'd answer, I just came back from my electronic-free vacation.

>The Edit2 is not understandable, I don't drink, but it sounds like I have. Sorry.

No problem, I hope you had a great vacation :D

> At first I thought you want the "Search text selection" command to use %s as a placeholder for the selected text instead of just appending the selected text to the end of the URL.

This seems like an useful addition.

> You are offering so great examples, so why not just offering 100 as it took me some time to figure out intuitive gestures. And there are better ones than mine for sure.

I can imagine publishing some example configs in the wiki, but I'm against setting so many as defaults. I'm convinced that most of the users aren't using more than ~25 gestures and I also think that only a minority uses more advanced gestures like letters or numbers. To me there are 2 reason for that:
- Gestures are most effective if they are short i.e. short enough so you can perform the gesture quicker than you could do the task the ordinary way.
- You need to be able to remember them. While gestures containing letters and numbers can be remembered quite easily, many other gestures are not self-explanatory. It's quite easy to learn a new gesture if it's bound to a task that you are doing very often, but typically the number of common tasks is very limited. Therefore all the gestures for uncommon tasks like "closing right tabs" or "move tab to start" (to refer to your examples) must be learned by heart.

Nevertheless I think your config file/image serves as a really good example for what Gesturefy or gestures in general are capable of.

> Some other commands or Add-ons work with keyboard-shortcuts like [ctrl]+[alt]+[any-key], but I think you have already written elsewhere, that it isn't possible.

Yes, sadly add-ons cannot trigger keyboard shortcuts.

> I meant a new Gesturefy-order to insert simple predefined text or code

So the command would behave like the "paste clipboard" command but instead of pasting the clipboard it would paste a custom string? 
This sounds interesting, but it's currently hard for me to think of any good use cases. I mean if you are writing 100 mails a day which are all starting with "Dear..." you are probably going to use a template or draft in order to make this process easier. "Address name etc." sounds more useful to me, but often times this information is split into multiple fields, so a single "paste text" command wouldn't help there. It's also overlapping a little bit with the "execute user scripts" command which of course requires some programming background.

**Comment by Robbendebiene** [comment]
This functionality is now available in [Gesturefy 3.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.0)
