### ISSUE TITLE
[Feature Request] gestures with left button only outside text

### ISSUE THREAD

**Issue by rinaldi6109** [Robbendebiene/Gesturefy#540]
I wish to use gestures using the left click, but this prevents me of selecting text and images. 
So, I ask if it is possible to start a gesture using the left click only if under the mouse there is'nt any text, that is, if it is started on an empty space in the web page.
(forgive me if I haven't used right and precise words)
Thank you.

**Comment by Robbendebiene** [comment]
I can understand the reason behind your feature request and with some exceptions it would probably be possible to implement it.
But it would take some effort while providing little benefit for most of the users and most importantly it would break the principle that gestures should (in theory) work everywhere on the page. Because of that I won't implement this feature.
I hope you can understand that.
