### ISSUE TITLE
Popup while drawing gestures

### ISSUE THREAD

**Issue by vgmielke** [Robbendebiene/Gesturefy#544]
When drawing a gesture, i often cannot finish the gesture because the right-click context menu appears. Sometimes everythig is fine, sometime i cannot even start the gesture , and sometimes the gesture gets interrupted while drawing. 
Seems to happen on almost all sites, i.e. https://www.bild.de/,la=de

Hard to get a screenshot. but often you see part of the gesture, partially hidden by the popup.

- Windows 10 Home Ver. 10.0.18363
- Firefox 81.0 (64-Bit)
-  Gesturefy, Version: 3.0.7

**Comment by Robbendebiene** [comment]
Are you using any other add-ons?

>  sometimes the gesture gets interrupted while drawing.

Do you mean that the context menu opens before you actually released the right mouse button?

> , sometime i cannot even start the gesture , and sometimes the gesture gets interrupted while drawing.

Please observe closer what the underlying elements are when this happens. For example gestures cannot be started from pure video elements or disabled input elements (#199)

If you can reproduce it reliably a video recording would also help, because I cannot reproduce it on the site you've linked.

**Comment by slumbergod** [comment]
The same thing is happening for me. I wanted to add firefox as a secondary browser. 
The moment I depress the right mouse button to draw a gesture, the right-click context menu pops up. This inhibits any mouse gestures that I try to draw under it.

I'm running firefox 81.01 on Manjaro Linux.

![gestures](https://user-images.githubusercontent.com/8507025/94967091-0a6dc800-04c4-11eb-9fd3-039e8e6ffb40.png)

**Comment by Robbendebiene** [comment]
@slumbergod Have you already tried all the points listed in the [troubleshooting guide](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting)?

**Comment by slumbergod** [comment]
Sorry, I will go through them shortly and confirm if any worked. I didn't realise there was a troubleshooting guide.

**Comment by thekingmonster22** [comment]
yes
