### ISSUE TITLE
Add option button on gesture edit page

### ISSUE THREAD

**Issue by byzod** [Robbendebiene/Gesturefy#551]
### Describe your matter in detail

It's not convenient to config gesture command, especially when debug user script
Please make it possible to config command directly in the gesture edit page

### Screenshots or further assistance
![1](https://user-images.githubusercontent.com/848607/97186857-cb8a1400-17dc-11eb-9f22-f8c6b3fc7695.png)
If you want to change user script, you need to click the command button, scroll all the way down and find what your command was (it won't focus you current command automatically), then click the little gear button

### Your System
- Operating system: win 10
- Firefox version: 82b9
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment]
While this is a very rare problem, since 99% of the commands do not offer such complex settings, we already thought about adding a clickable gear icon multiple times. The last reasons we thought about it was, that it would benefit the understanding that certain commands offer additional settings. This is more or less solved now due to the added gear icons.

We always feared that the icon change in the button might be confusing to users. At least it wouldn't be clear that the icon is clickable, since neither the current icon nor the icon on the select fields are clickable (they are just indicators).
So I'm still not sure if this is a good idea.

**Comment by byzod** [comment]
> since 99% of the commands do not offer such complex settings

Yes, so I think extra button just for user script is enough

**Comment by Robbendebiene** [comment]
> Yes, so I think extra button just for user script is enough

Adding behavioural exceptions to the UI is basically a No-Go, so I won't implement that.

> Or scroll to the current command automatically is ok

While this is would be a good solution for the problem, it's weird if you just want to change the command. Because every time you change a command you start at a different position. Since changing commands is a more common task than changing the settings of a command, the drawback outweighs the benefit.

**Comment by Robbendebiene** [comment]
This is now available in [Gesturefy 3.2.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.0)

**Comment by byzod** [comment]
> Adding behavioural exceptions to the UI is basically a No-Go

So why it's Yes-Go now?

> Since changing commands is a more common task than changing the settings of a command, the drawback outweighs the benefit.

For what the benefit outweighs the drawback now?

**Comment by Robbendebiene** [comment]
> So why it's Yes-Go now?

The implemented solution works across all commands that provide settings, which means it's consistent in contrast to your proposal.
I never said that I'm against fixing this issue in any way.

> For what the benefit outweighs the drawback now?

Have you even looked at the current UI? It still doesn't scroll to the command as you've proposed, instead there is now an extra gear icon/button to the right if the command contains any settings. Clicking the icon will open the settings of this particular command.
