### ISSUE TITLE
Show an easy help screen with all my gestures

### ISSUE THREAD

**Issue by Sopor** [Robbendebiene/Gesturefy#553]
I always forget my gestures so i wondering if it is possible to make some kind of quick gesture help that can be easy to bring up on the screen?

Now i have a picture that i open when i forget, but that is not working very good. That is why i ask you to see if you can make something that is much better than a simple jpg picture.

It should be possible to add a gesture to it (I add an easy gesture i do remember) and it was then visible in a few seconds or until i click on it.

**Comment by Robbendebiene** [comment]
This is totally possible. Even though it's not that hard it still requires a decent amount of work.
The only part I don't understand is:

> It should be possible to add a gesture to it (I add an easy gesture i do remember) and it was then visible in a few seconds or until i click on it.

Where do you want to add a gesture?
What are you clicking?

**Comment by Sopor** [comment]
It was only a suggestion to show the help by doing a gesture and to close the help i click on it to close it, but i assume you will find some fancy way to show this gesture help :)

**Comment by Robbendebiene** [comment]
I decided to not implement a separate command for this, because it's a pretty specific use case which is not implemented without effort. However below I provide 2 solutions that might work for you, so I hope you aren't that mad at me :)

**Option 1**
Since the new [version 3.2.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.0) your gestures are displayed by default when opening the settings page of Gesturefy. The settings page in return can be opened via the "Open Gesturefy Settings" command.

**Option 2**
As an alternative you can use the "User Script" command to show an image with the following script code:

```
const url = "https://themes.webberwebber.com/time/files/2013/07/clouds-4-pan.jpg";

const img = document.createElement("img");
img.src = url;
img.onblur = () => img.remove();
img.tabIndex = -1;
img.style = `
  position: fixed;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  max-width: 100vw;
  max-height: 100vh;
`;
document.body.append(img);
img.focus();
```

You have to replace the image url (note that a local file wont work). If you don't want to upload your image/screenshot you can use a data url that can be obtained [here](https://ezgif.com/image-to-datauri) for example. The data url will be quite long because it contains all the image information/pixels, but you can simply replace it with the current url in the script.
In the settings of the user script command you best use "top frame".
