### ISSUE TITLE
Add double and triple click feature for touchpads

### ISSUE THREAD

**Issue by gonzaarcr** [Robbendebiene/Gesturefy#558]
This extension is great for touchpad, since moving it all over the screen is annoying, and a gesture is more natural. But I had to map it to left click (otherwise I have the use the physical button). It works with a double click (which, in touchpad in single click). I’d like it to work on double and triple click (would be 3 and 4 on touchpad) and they shouldn’t be mutually inclusive (a double click isn’t a single click). So if you choose double click and want to select text with triple click it shouldn’t be triggered.

**Comment by Robbendebiene** [comment]
Sorry, but I don't understand this:

>  It works with a double click (which, in touchpad in single click). I’d like it to work on double and triple click (would be 3 and 4 on touchpad) 

On my touchpad one tap/click equals one mouse click.

**Comment by gonzaarcr** [comment]
If you tap and move you are doing just a move, if you double tap and move is a click and move (like, to dragging a file). To be precise, is a tap and a half, because you don’t release. If you triple tap and move is a double click and move, and so on.

I’m not talking about the physical button, with that one the relation is 1:1, but you have to use two hands or use the thumb somewhat uncomfortable, is not as smooth as the emulated click.

**Comment by Robbendebiene** [comment]
> If you tap and move you are doing just a move, if you double tap and move is a click and move (like, to dragging a file). To be precise, is a tap and a half, because you don’t release. If you triple tap and move is a double click and move, and so on.

All right, I got it.

> I’m not talking about the physical button, with that one the relation is 1:1, but you have to use two hands or use the thumb somewhat uncomfortable, is not as smooth as the emulated click.

I would love to make gestures more accessible to touchpads, but your suggestion has a fundamental problem. A double click leads always (see exception below) to a single click as well, because it is impossible to predict wether you want to perform a single or a double click. For touchpads therefore a tripple click also always fires a double click. Of course the obvious solution for this is to add a little delay to every click event and ignore it if a followup event occurs. However browsers don't support delaying events nor triggering true click events programmatically.

The only thing that  seems to work on touchpads is _tap_ > _release_ > _tap_ (almost a double click). This (at least for me) doesn't trigger a link navigation, probably because there is some built in delay. However once you add another tap (almost a triple click) the browser will open the underlying link.
