### ISSUE TITLE
Enhancement: Stop loading ALL

### ISSUE THREAD

**Issue by KenseiSins** [Robbendebiene/Gesturefy#560]
hi sorry for popping up again, maybe I should formulate a list of these first and then making a mega enhancement suggestion post instead of these one-offs... yeah I'll do that next post. sorry. lol

UM YES WE DO HAVE A "STOP LOADING" GESTURE, BUT ITS ONLY FOR THE CURRENT TAB, WHICH IS (ill stop allcapping now) perfect for it's counterpart gesture "Reload page", however for "Reload All Pages" It has no friend. :( 
to which I declare (suggest) that a "Stop loading all pages" Gesture must also be made so that the pair may be a heaven's matched. 

Also I'm curious, what does your gestures look like? and do you use all of them? It's quite the challenge to come up with a gesture grid for all of them, but I suppose it can be done. I ask also because I'm eager to share mines. Intruigued? 👯 🗡️ ☠️  (Dance of Death) ohohoho.

**Comment by Robbendebiene** [comment]
> hi sorry for popping up again, maybe I should formulate a list of these first and then making a mega enhancement suggestion post instead of these one-offs... yeah I'll do that next post. sorry. lol

Keeping them separated is the right way to go. So stick with that :)

> UM YES WE DO HAVE A "STOP LOADING" GESTURE, BUT ITS ONLY FOR THE CURRENT TAB, WHICH IS (ill stop allcapping now) perfect for it's counterpart gesture "Reload page", however for "Reload All Pages" It has no friend. :(
> to which I declare (suggest) that a "Stop loading all pages" Gesture must also be made so that the pair may be a heaven's matched.


I agree that it would fit as a counter part, but is there really a use case for this? I personally never encountered a situation where the loading of multiple tabs needed to be stopped.
An additional problem is that the "Stop Loadig" command is limited technically. It only works if the page already is somewhat loaded and just didn't finished loading yet or loaded some content later on. Since gestures only work on partially loaded pages (same as the Stop Loading command) this isn't a problem. However the StopAllLoading command would suffer from this limitation. It may also be used to stop tabs from loading where gestures aren't possible at the moment (because the sites hasn't partially loaded yet). Thus StopAllLoading would fail for these tabs which users might interpret as a bug.
Maybe "Reload All Pages" likes to remain single after all?


> Also I'm curious, what does your gestures look like? and do you use all of them? It's quite the challenge to come up with a gesture grid for all of them, but I suppose it can be done. I ask also because I'm eager to share mines. Intruigued? dancers dagger skull_and_crossbones (Dance of Death) ohohoho.

I use all of my gestures (see below) except the "go to first/last tab" because when I need them I always forget that I have a gesture for that.
My rule is simple: for every **frequently** done task that can be accomplished by a gesture more quickly, use a gesture :) If you are only rarely doing that task, having a gesture is cool, but you will have a hard time remembering it. In my opinion it doesn't make sense to map every possible command to a gesture. But since there exists hardcore keyboard shortcut users, I don't see why there shouldn't exist some hardcore gesture users as well :D

![grafik](https://user-images.githubusercontent.com/13716661/102483982-e1da8080-4065-11eb-895f-95397c16ad65.png)

>  I ask also because I'm eager to share mines. I

I'm always interested in how other people use Gesturefy :)

**Comment by KenseiSins** [comment]
I see you have made use of diagonally sorting your functions. Thats too trippy for me, mines are much more intuitive, Draw an F, for full screen draw a B for bookmark xD  I use the 4 cardinal points Up down left and right, but to increase my options, I’ve made it so that you need to draw a U in that direction, backwards in that direction, or to and froe. And then a combination of that. Its sort of like counting with 1 hand, you can go systematically, but if you split your fingers to segments, suddenly you can do much more gestures, it really is the ascii system but picturized lol

AND YES THERE IS A FUNCTION FOR IT, I had 99 tabs of videos open, and I accidentally reloaded them all and my computer slowed down LOL. I guess I would just use keyboard or mouse clicks to stop all, ur right. A gesture isn’t needed. Now how do I gesture thank you to you. :D



[cid:image004.png@01D6D571.DCBEF090]
https://gyazo.com/d7cbcabd69df0a588490449ea5e3d577
[cid:image003.png@01D6D571.B809D080]
https://gyazo.com/5293cebbb54c15f7e77a4de8392bf9a0
[cid:image002.png@01D6D571.A21FEBB0]
https://gyazo.com/5dab47daf09ecc32e0b87b695926ad02
[cid:image001.png@01D6D571.8EB0CAE0]
https://gyazo.com/c721b862f462c347949ff249c2d8d835











Warmest Regards, C. “Chihiro” K.
⚊ ⚋ 𝌀
⚌ ⚍ ⚎ ⚏ 𝌁 𝌂 𝌃 𝌄
𝌅
☰ ☱ ☲ ☳ ☴ ☵ ☶ ☷
𝌆 𝌇 𝌈 𝌉 𝌊 𝌋 𝌌 𝌍
𝌎 𝌏 𝌐 𝌑 𝌒 𝌓 𝌔 𝌕
𝌖 𝌗 𝌘 𝌙 𝌚 𝌛 𝌜 𝌝
𝌞 𝌟 𝌠 𝌡 𝌢 𝌣 𝌤 𝌥
𝌦 𝌧 𝌨 𝌩 𝌪 𝌫 𝌬 𝌭
𝌮 𝌯 𝌰 𝌱 𝌲 𝌳 𝌴 𝌵
𝌶 𝌷 𝌸 𝌹 𝌺 𝌻 𝌼 𝌽
𝌾 𝌿 𝍀 𝍁 𝍂 𝍃 𝍄 𝍅
𝍆 𝍇 𝍈 𝍉 𝍊 𝍋 𝍌 𝍍
𝍎 𝍏 𝍐 𝍑 𝍒 𝍓 𝍔 𝍕

**Comment by Robbendebiene** [comment]
I'm closing this issue for the stated reasons. It might be revisited if the Firefox API becomes capable of properly stopping tabs from loading.
