### ISSUE TITLE
Please optimize the logic of url number increase and decrease

### ISSUE THREAD

**Issue by Dynamith** [Robbendebiene/Gesturefy#571]
### Describe your matter in detail

Sometimes there is more than one number in the URL, and the last one we need to change is often the last one. The logic of the current gesture is to change the first one. Could you modify it?

### Your System
- Operating system: windows10 2004
- Firefox version: 85.0.2
- Gesturefy version: 3.1.1

**Comment by Robbendebiene** [comment]
There are a lot of different expectations how this command should work (see here: https://github.com/Robbendebiene/Gesturefy/issues/367). Because of that I should never have implemented this command in the first place.

Nevertheless I guess increasing the last number is what most people would expect so I'm changing this. If you want to use this command extensively I recommend using the user script I provided in the other issue.

**Comment by Dynamith** [comment]
Yes, I think the last number is the simplest and quickest solution. If I encounter a complicated situation, I will use your script or adapt it myself. And I think it's not good to integrate too many complex functions like your script in addon. It should be solved by writing a script by ourselves, or it would be better if a script sharing function is established, so that additional scripts can be used more simply and quickly.

**Comment by Robbendebiene** [comment]
This change is now available in the latest release ([version 3.1.2](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.2))
Read more about it here: https://github.com/Robbendebiene/Gesturefy/wiki/Regular-Expressions#increase--decrease-url-number
