### ISSUE TITLE
Open link in new tab and switch to the new tab

### ISSUE THREAD

**Issue by buddyackerman** [Robbendebiene/Gesturefy#572]
I really like the open link in new tab feature but I would like to enhance it by making the new tab the active tab, why else would I open a new tab if I didn't want to see it.  Maybe make a separate command for open and activate if you still want to have just open as an option, although I'm not sure why I would want to open a link but not view that tab.

### Your System
Firefox version: 86.0
Gesturefy version: 3.1.1

**Comment by Robbendebiene** [comment]
This is already possible. Just reassign the command and activate the setting "focus new tab".

**Comment by buddyackerman** [comment]
I don't see a setting called "focus new tab".  If you're talking about the built-in FF option then that's already turned on.

**Comment by Robbendebiene** [comment]
Please create a new gesture and assign the "open link in new tab" command. Either make a single screen recording or a screenshot for every intermediate step and post them here.

**Comment by nolnolnolnol** [comment]
I have the same issue that I prefer to open homepage in a new tab then  go to the homepage. Although I can do it by “open custom URL in new tab” command. If so, the "Open homepage" dose not exist.
![2021-03-19 230713](https://user-images.githubusercontent.com/27913929/111803103-b176dc80-8909-11eb-82a1-62176f1b75a2.png)

**Comment by Robbendebiene** [comment]
@nolnolnolnol I don't understand your problem. Since you are referring to opening a specified URL I also don't think your problem is related to this one.
If you want to use the "open homepage" command to open your homepage in a new tab then you should use (as you suggested) the "open custom url in new tab" command. The open homepage commands differs in it's behaviour from the "open custom url" command as it will open a new tab when executed on a pinned tab (like the Firefox homepage button does).
