### ISSUE TITLE
Show gesture preferences in overview

### ISSUE THREAD

**Issue by SebastianZ** [Robbendebiene/Gesturefy#588]
Currently it takes several steps to see which settings are set for a gesture. In my case, this were URLs assigned to gestures to open them in new tabs.

### Screenshots or further assistance
Examples of two gestures to open URLs in new tabs.

![Gestures opening a URL in a new tab](https://user-images.githubusercontent.com/958943/119968556-eeb4b600-bfad-11eb-86d0-6b17f78f0ac7.png)

If all the additional information makes the overview too crowded, maybe it could be displayed in a tooltip instead.

### Your System
- Operating system: Windows 10 20H2
- Firefox version: 88.0.1
- Gesturefy version: 3.1.2

Sebastian

**Comment by Robbendebiene** [comment]
I understand your problem, but for this type of commands you should give a meaningful title instead. Showing all the options wouldn't make it immediately clear what the gesture does either, especially when we are talking about commands like "execute user script" or "search text selection".

<img width="500" src ="https://user-images.githubusercontent.com/13716661/119971108-d8f4c000-bfb0-11eb-83a1-d9d4a252929d.png">

The gesture settings page is designed to provide a quick overview. Since settings are normally only required once on setup I think it's reasonable to hide this kind of information in favor of the overview. I agree though that accessing this information is cumbersome. It's 3 levels deep and requires probably some scrolling too. I suppose the average user would expect the settings or at least access to them inside the popup.

The solution I like the most is providing a quicker way to access the settings of a command by adding a clickable gear icon to the command select button (https://github.com/Robbendebiene/Gesturefy/issues/551) This way it would only be 2 levels deep without any scrolling.

Regarding a tooltip, yes it would work, but I try to avoid them where I can especially when the information can be found else where/is redundant.

So I think this can be "solved" by using a title for the gesture and the quick settings access I've described, but let me know what you think.

**Comment by SebastianZ** [comment]
@Robbendebiene Thank you for your extremely quick and detailed answer!

For some reason I missed that you can specify a custom title for the gestures. That's sufficient to solve my use case and I guess most others, too. With that it's just a matter of applying a proper title (which can contain some info about the different settings).

I'd still like tooltips with additional information, though I admit they might not the best option UX-wise for everyone.

I agree with you that moving the settings one level up in combination with providing a title basically solves the mentioned issue. So I close this issue in favor of #551.

Sebastian
