### ISSUE TITLE
[Feature Request] open different types of clipboard content differently

### ISSUE THREAD

**Issue by m1karii** [Robbendebiene/Gesturefy#589]
- if (clipboard contains URL or address of a local item (file)) {open it}, otherwise if (the content of clipboard is text) {search for it}. I'm not aware of any way you would be able to do that currently. There would be 2 commands one for current tab and one "in new tab".
- change "Search clipboard" command to 2 commands - one for current tab and one "in new tab".
- i dont know if this is a software limitation or if i need to do this somehow manually but I'd like to be able to enable Gesturefy in ALL tabs including tabs like "about:*" tabs (e.g. about:home) and "Extension" tabs (e.g. Gesturefy settings page/tab)

**Comment by Robbendebiene** [comment]
> if (clipboard contains URL or address of a local item (file)) {open it}, otherwise if (the content of clipboard is text) {search for it}. I'm not aware of any way you would be able to do that currently.

This already has been requested here https://github.com/Robbendebiene/Gesturefy/issues/523 and will be available soon when the "Multi purpose command" lands. You can already read about it here: https://github.com/Robbendebiene/Gesturefy/wiki/Multi-purpose-command

> change "Search clipboard" command to 2 commands - one for current tab and one "in new tab".

Yes this makes sense, since this separation exists for basically every other command except search commands.

> i dont know if this is a software limitation or if i need to do this somehow manually but I'd like to be able to enable Gesturefy in ALL tabs including tabs like "about:*" tabs (e.g. about:home) and "Extension" tabs (e.g. Gesturefy settings page/tab)

This is a common add-on limitation and also mentioned in the add-on description. (Some details can be found here: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#gesturfy-is-not-working-at-all)

**Comment by m1karii** [comment]
> This is a common add-on limitation and also mentioned in the add-on description. (Some details can be found here: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#gesturfy-is-not-working-at-all)

Is it possible to somehow go around this limitation?
Is it possible to go around this limitation locally manually?

**Comment by Robbendebiene** [comment]
I'm not aware of any option. You can only enable extensions on restricted websites like mozilla addons etc.. (#547)

**Comment by Robbendebiene** [comment]
This is now available in [Gesturefy 3.2.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.0)
