### ISSUE TITLE
image "up-down" looks like "down"

### ISSUE THREAD

**Issue by Tom19rgr74** [Robbendebiene/Gesturefy#596]
in 'gestures', the image for 'up-down' only shows a down-arrow. There is no difference between the (image of) the down-gesture and the up-down-gesture'

- firefox 78.11.0esr (64-bits)
- Gesturefy version: 3.1.1

**Comment by Robbendebiene** [comment]
You've probably transitioned from an older version of Gesturefy (2.0) to the newer 3.x. So far no solution for this problem is known or has been suggested. Most people simply redraw their gestures with a slight offset like this /\ . Other than that you should be able to follow the movement of the arrow on hover and thus be able to distinguish between the two gestures.

**Comment by Tom19rgr74** [comment]
I probably had 2.0 before since I'm a long time happy user, thanks!
The mouse-over worked, Redrawing like /\ worked well.
Suggestion: when importing/upgrading gestures with overlaps like this, add a very small angle. I suppose a left-to-right direction is good when the used language reads left-to-right too.

**Comment by Robbendebiene** [comment]
Sounds like a good suggestion. However since ~99% of the user's already transitioned to the new version it's quite late for this implementation. I'm probably too lazy for this, but we'll see 🙂

>  I'm a long time happy user, thanks!

Glad you like Gesturefy.

I'm closing this ticket for know, feel free to reopen and post any further ideas regarding this topic here.
