### ISSUE TITLE
sendRemoveListener on closed conduit {506e023c-7f2b-40a3-8066-bc5deb40aebe} errors

### ISSUE THREAD

**Issue by def00111** [Robbendebiene/Gesturefy#602]
https://github.com/Robbendebiene/Gesturefy/blob/dbbd507cc6f06b38defe4b7d431807b499d0d234/src/core/workarounds/content.bundle.js#L270-L281

Can you add the [fix](https://github.com/sienori/simple-translate/commit/b5d5970a854fd7f96ca42842d0096d2ee8e6cda8
) in your code to stop the errors in the  browser console?

![firefox_FWdLqtNjPG](https://user-images.githubusercontent.com/10849366/130338197-9cafe53f-54c5-4601-ae99-f0cf876fddc1.png)

**Comment by Robbendebiene** [comment]
Thanks for the report.
If I try to remove the onChange listener on `unload` I get the following error: `Error:WebExtension context not found!`
While the `beforeunload` event suppresses the error successfully, the "unloading" of the page can still be canceled by the user at this point. So this would be to early to remove the onChange listener.

My resolution so far was to wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1633315

I don't want to move the listener to the background script, since this would destroy the idea of a single config manager class.
If you have another idea please let me know.

**Comment by def00111** [comment]
Does the `pagehide` event work?

**Comment by Robbendebiene** [comment]
Unfortunately it suffers from the same problem as the `unload` event.

**Comment by Robbendebiene** [comment]
I'm closing this since https://bugzilla.mozilla.org/show_bug.cgi?id=1633315 should fix this problem.
