### ISSUE TITLE
How to make bookmarks appear ?

### ISSUE THREAD

**Issue by fdepub** [Robbendebiene/Gesturefy#607]
### Describe your matter in detail
Hello, I'd like to know if there is a shortcut to make bookmarks appear ?

### Your System
- Operating system: Windows 7 Pro
- Firefox version: 91.0.2 (64 bits)
- Gesturefy version: 3.2.0

**Comment by Robbendebiene** [comment]
Hi, thanks for your feature request.
Unfortunately this is not possible, because extensions do not have the power to open the bookmarks sidebar, the bookmarks popup or anything like that.

Similar issues regarding the bookmark sidebar:
- https://github.com/Robbendebiene/Gesturefy/issues/496
- https://github.com/Robbendebiene/Gesturefy/issues/352
- https://github.com/Robbendebiene/Gesturefy/issues/141
and the add new bookmark popup:
- https://github.com/Robbendebiene/Gesturefy/issues/205
