### ISSUE TITLE
Bug when holding down RMB+LMB

### ISSUE THREAD

**Issue by AlperK** [Robbendebiene/Gesturefy#615]
### Your System
- Operating system: Windows 10 
- Firefox version: 93.0
- Gesturefy version: 3.2.1.

Hold down RMB, then sweep down LMB while still holding down RMB, then indicators for the Gesture still stays on the page, even though the Gesture is failed already.
https://imgur.com/a/z635vXB

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll fix this.

**Comment by Robbendebiene** [comment]
This should be fixed in [Gesturefy 3.2.2](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.2).

Note that [Gesturefy 3.2.2](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.2) also introduced a long planned feature, which is the cancellation of the current mouse gesture by pressing another mouse button.
