### ISSUE TITLE
Restore tab command does not work

### ISSUE THREAD

**Issue by Bahoslav** [Robbendebiene/Gesturefy#627]
Hello. 
Restore tab command does not work, nothing happens when applying gesture bonded to mentioned command.
It shows the name of command but to no avail.

- Operating system: Win7
- Firefox version: 94.0.1 64bit
- Gesturefy version: 3.2.4

**Comment by Robbendebiene** [comment]
Can you please check if Firefox build in restore tab functionality works (there is for example a history icon where you can display the last closed tabs, this shouldn't be empty).

Also please check if Gesturefy has the permission to access recently closed tabs.

![grafik](https://user-images.githubusercontent.com/13716661/142766488-b27dc8fd-be58-43c8-8b6b-e5fede8eef21.png)

**Comment by Bahoslav** [comment]
Restore functionality works, I am using keyboard short-cut without problem.  I have checked and permissions are enabled.

**Comment by Robbendebiene** [comment]
Okay in this case I need a console log, since I cannot reproduce the problem.
Can you please
-  Enter `about:devtools-toolbox?type=extension&id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D` in your address bar
-  Switch to the "Console" tab in the top bar
-  Click the "bin" icon to clear the console
- Try the restore tab gesture in a different tab and head back to the console tab afterwards
-  Copy and paste all outputs into the issue here (or make a screenshot)

Btw. When did the problem first occur? Did it work before?

**Comment by Bahoslav** [comment]
![GFConsole](https://user-images.githubusercontent.com/58751643/142780889-69012088-a686-4128-a8d0-073a36dacebc.png)
There were some updates on the addon an ff right? It started about a week ago, can't really tell but I am a avid user yes it worked before.

**Comment by Robbendebiene** [comment]
Thanks for the log! Unfortunately I'm not able to get much out of the error.

Can you please go to `about:debugging#/runtime/this-firefox` > click "load temporary addon" and choose this [zip file](https://github.com/Robbendebiene/Gesturefy/files/7597714/debug.zip). After this please repeat the steps you followed previously. This time there should be more output in the console.



> There were some updates on the addon an ff right? It started about a week ago, can't really tell but I am a avid user yes it worked before.

Right, though I haven't touched this code, so I believe this error might be caused by some Firefox internals.

**Comment by Bahoslav** [comment]
Hello. I guess we can close the issue because it started to work again but was a annoying two weeks without it. I've also tried to check if error appears in console log but it doesn't happen. I haven't change anything in the system.
Code moves in a mysterious way.

**Comment by Robbendebiene** [comment]
Thanks for the update.
So it probably was a Firefox bug or some damaged database. We probably will never know, but I'm glad it works now!
