### ISSUE TITLE
Great Addon, suggestion, {Popup} All Tabs with an (x) button to close the tab.

### ISSUE THREAD

**Issue by AliAsiri20** [Robbendebiene/Gesturefy#631]
I love Gesturefy for firefox and chrome so much. I can't live without it. The (popup) all tabs feature is great. It allows me to browse tabs quickly in no time. However, in many cases I need to close some tabs when it is open and can't figure a way to do so. I tried the mouse middle click, tried delete key, right mouse click, but non of them helped. 

It would be great if there was an (x) button on each tab to close the tab. 

There are other tabs addons that allows to do so, but the one implemented in Gesturefy is light quick well designed. 

Thank you so much for the developer who made this excellent addon.

**Comment by AliAsiri20** [comment]
The middle click to close a tab is better than an (x) button I think.

**Comment by Robbendebiene** [comment]
Thanks for your kind words, I really appreciate it!

Popup commands are more "agnostic" to their contents then you might think. Each popup command only provides one single action (focus tab, search selected text etc.) on a set of data. So while I have to admit that your idea may be nice in practice, it goes against the above principle. Implementing this would take quite some effort and also bloat the add-on, therefore such things should be handled by a different add-on (which might be controlled/activated via a Gesturefy gesture).


I hope you can understand this.

What I could do is adding an extra popup command where each click on an item will close the tab, but in this case you will need a separate gesture and it will also feel weird because the entries/tabs won't disappear from the popup when clicking them.

**Comment by AliAsiri20** [comment]
Yes, that was clear enough. Thank you so much Robben. Still Gesturefy is the one to go to to flip quickly through tabs. Even at times when I need to do diagnostics and disable extensions, Gesturefy is the last one to disable.

**Comment by Robbendebiene** [comment]
Thanks again!
Feel free to reopen this issue if you have any further questions or suggestions regarding this particular topic.
