### ISSUE TITLE
Restore Tab

### ISSUE THREAD

**Issue by kjell46** [Robbendebiene/Gesturefy#634]
### Your System
- Operating system: Windows 10
- Firefox version: 96.0.2
- Gesturefy version: 3.2.4

Hi,
About a week ago, Restore tab gesture stopped working. Can't find a way to make it work again.
Tried changing gesture, gone through all settings - to no avail...
K

**Comment by Robbendebiene** [comment]
There are a lot of existing issues about this topic. None of them were caused by Gesturefy. Therefore the bug most likely is somehow caused by Firefox session management internals or its API.

Make sure the "access recently closed tabs" permission is granted. You can check this under `about:addons` > Gesturefy > Permissions

Maybe one of the resolution from other users will help you:
- https://github.com/Robbendebiene/Gesturefy/issues/627
- https://github.com/Robbendebiene/Gesturefy/issues/612
- https://github.com/Robbendebiene/Gesturefy/issues/608
- https://github.com/Robbendebiene/Gesturefy/issues/577

**Comment by kjell46** [comment]
<Hi again,
I have gone through and tried all your suggestions, only to find that it still doesn't work. Exhausting work, but the Firefox 'reopen' command still works, so I won't bother you again about this issue. Still keeping Gesturefy, since the rest of it works just fine. Any other suggestions on solving this are welcome...
thanks
Kjell

**Comment by Robbendebiene** [comment]
That's unfortunate.
Did you change anything when the problem first occurred? For example a Firefox update?

Have you tried Gesturefy using a fresh profile?

Maybe a console log will help figuring out what's going wrong. Therefore please:

-  Enter `about:devtools-toolbox?type=extension&id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D` in your address bar
-  Switch to the "Console" tab in the top bar
-  Click the "bin" icon to clear the console
-  Try the restore tab gesture in a different tab and head back to the console tab afterwards
-  Copy and paste all outputs into the issue here (or make a screenshot)

**Comment by kjell46** [comment]
Fixed! Firefox new profile, and re-adding all add-ons (Gesturefy too), and now it works the way it should. Took a little elbow grease, but when finally done I feel it was worth it. Fingers crossed it won't happen again...
Bye now
K

**Comment by Robbendebiene** [comment]
All right, hope the problem won't occur any time soon :)
