### ISSUE TITLE
quick way to switch to the last N tab

### ISSUE THREAD

**Issue by Dituar** [Robbendebiene/Gesturefy#648]
in continuation https://github.com/Robbendebiene/Gesturefy/issues/647
Or another quick way to switch to the last N tab. Maybe this way is faster for the user  and easier to implement. 
Draw gesture with a right-click the number "2" to switch to the pre-previous tab (there is a separate gesture for switching to the previous tab), draw number "3" to switch to the pre-pre-previous tab, and so on...

I want to switch between the last tabs faster, more faster))
Maybe someone can think of a better way?

- Operating system: win 7 64
- Firefox version: 103.0.2 (64 bit)
- Gesturefy version: 3.2.5

**Comment by Robbendebiene** [comment]
I think the approach has a usability problem.
Let's consider 3 tabs a, b, c listed in the order they have been visited (c is the current tab, b the last visited etc.)
Switching to the last visited tab will switch from c to b. Doing the same thing again will switch from b to c. So far so good.

But switching to the "pre-pre-previous" will switch from c to a. Doing this again will switch from a to b and again from b to c. What I want to illustrate is that switching to any "pre-pre-.." tab will rearrange the tab order in an elusive way. Sure for this example with only 3 tabs in total and two steps back it's still understandable, but it will get complicated quickly.

Ultimately I think that for switching between tabs quickly there needs to be a (limited) view/list of the last viewed tabs in order to make tab switching quickly and comprehensible. Firefox has (or had?) a very good build-in feature for this, but it's controlled via keybaord: https://support.mozilla.org/en-US/questions/955292
