### ISSUE TITLE
New window gesture not opening a new window

### ISSUE THREAD

**Issue by bestekov** [Robbendebiene/Gesturefy#657]
### Describe your matter in detail
I have a gesture (draw up arrow) to open a new window and it stopped working. If I turn on detection of the gesture, it shows that the new window command was invoked, but no new window is opened.

ctrl+N still opens it.

Separately on another computer (same versions) it _does_ work? I have tried restarting Firefox but does not resolve the issue.

### Your System
- Operating system: Windows 10
- Firefox version: 105.0.1
- Gesturefy version: 3.2.6

**Comment by Robbendebiene** [comment]
Hi, in this case I need a console log, since I cannot reproduce the problem.

Can you please
-  Enter `about:devtools-toolbox?type=extension&id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D` in your address bar
-  Switch to the `Console` tab in the top bar
-  Click the "bin" icon to clear the console
- Try the open new window gesture in a different tab and head back to the console tab afterwards
-  Copy and paste all outputs into the issue here (or make a screenshot)

**Comment by bestekov** [comment]
Unfortunately a just a rather vague `unexpected error occurred`

![2022-10-03_144510](https://user-images.githubusercontent.com/4909619/193654559-8b2fc414-a360-47e9-8bdb-
71d89ba17fb4.png)

**Comment by Robbendebiene** [comment]
This must be some Firefox API internal error. Can you reproduce this in the same Firefox browser instance on a clean profile?

**Comment by bestekov** [comment]
I installed on a brand new Windows 11 laptop and signed in to my firefox account and had the same issue.

I tried launching in a clean new profile and it works fine.

Any suggestions on how to fix my main firefox profile? It has all of my other data, so I can't just start over clean.

**Comment by Robbendebiene** [comment]
If it is caused by a "corrupted" Gesturefy config simply re-creating the gesture/command should solve the problem.
If it is caused by some Firefox profile settings then I have no good advice other than tracking down the root of the issue.

[This is the code Gesturefy runs](https://github.com/Robbendebiene/Gesturefy/blob/master/src/core/commands.mjs#L735-L739) - there is basically nothing that can be done wrong there.
