### ISSUE TITLE
Icons HUD

### ISSUE THREAD

**Issue by zaum** [Robbendebiene/Gesturefy#669]
It would be great if the name of the gesture could be an icon. It would look more elegant. In a slightly rounded box.

https://fonts.google.com/icons?icon.category=UI+actions&icon.style=Rounded

**Comment by Robbendebiene** [comment]
I agree that it could look nice, but I'm not sure if it would be very beneficial.
The easiest solution would be to allow the usage of a custom font. But since one can already use UTF8 Symbols and emojis I would argue that it is already kinda possible.

[Bildschirmaufzeichnung vom 2023-03-09, 17-51-11.webm](https://user-images.githubusercontent.com/13716661/224098442-04cd5b22-a63c-4b76-9b9e-a1bb08d2d0a3.webm)

**Comment by zaum** [comment]
Great! Thank you, i didnt know its possible. :)

**Comment by Robbendebiene** [comment]
Closing this as it is at least partially already possible. A dedicated icon support is out of scope for this add-on, but might still be possible in the future due to custom CSS styling.
