### ISSUE TITLE
very strange behavior on my own website

### ISSUE THREAD

**Issue by protektwar** [Robbendebiene/Gesturefy#675]
### Describe your matter in detail
The problem is simple, when even I want to use gesturefy on my own website I get the following (see the screenshot)

### Screenshots or further assistance
![image](https://github.com/Robbendebiene/Gesturefy/assets/45262264/7721b016-4345-4941-bb89-a8e2122addb9)

### Your System
- Operating system: Ubuntu 22.04.2 LTS
- Firefox version: 113.0.1 (64-bit)
- Gesturefy version: 3.2.7

**Comment by Robbendebiene** [comment]
You will notice that this happens as well if you use the Firefox Screenshot tool. This is because webextensions need to manipulate the DOM if they want to show anything to the user wherefore they obviously can affect the website itself. Disabling all of Gesturefy UI features resolves this as expected. Maybe you have some sort of DOM Mutation Observer that gets triggered. I don't know. Either way there is nothing I can do on my side.
