### ISSUE TITLE
Gesturefy does not recognize links embeded in Youtube video thumbnails

### ISSUE THREAD

**Issue by tommobile14** [Robbendebiene/Gesturefy#684]
Windows 10, Firefox 117 64.

I have a gesture to Open Link in new Tab. It works fine in most situations. But on Youtube Main page, the gesture only works if I initiate it from the video title (the words part), but does nothing if I initiate it from the video thumbnail. Even though both the title and the thumbnail follow the same link.

The odd thing is, if I already open a Youtube video and then initiate the gesture on the Suggestion video thumbnails on the side, it works.

This issue is only with Youtube Main page. Gesturefy works fine with other video thumbnails on other platforms like Vimeo or Twitter.

**Comment by Robbendebiene** [comment]
Hi thanks for the detailed report.
I think I can fix this.

The reason is that youtube only activates the thumbnail link on mouseover, but Gesturefy is collecting the data at the end of the gesture (at this time youtube has removed the link).

This bug has been occurred [before](https://github.com/Robbendebiene/Gesturefy/issues/427) but was fixed back then. It probably reoccurred because of youtubes new "live preview" I wonder if I had a good reason not to gather all the data on gesture start and rather did it on gesture end 🙈

**Comment by tommobile14** [comment]
Thank you for the reply.

If "Gesturefy is collecting the data at the end of the gesture" then how does it understand when the gesture starts from the link itself? Surely it has to collect data both from the start and the end of the gesture?

I actually just tried to do the same gesture, this time starting from outside and inside the thumbnail, making sure both gestures end on the thumbnail. Both fail to register.

Hope you'll iron out this bug. Great work on this add-on.

**Comment by Robbendebiene** [comment]
> If "Gesturefy is collecting the data at the end of the gesture" then how does it understand when the gesture starts from the link itself? Surely it has to collect data both from the start and the end of the gesture?

When a gesture is performed Gesturefy stores the starting point _element_. But the actual collection/extraction of the data from the _element_ (like the link url) happened when the gesture was finished. At this moment though the element might have been removed or altered by the website.

This should be fixed in the new [Gesturefy version 3.2.9](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.9) which should be available soon.
