### ISSUE TITLE
Feature Request: Some enhancements on selected text search

### ISSUE THREAD

**Issue by Hipd** [Robbendebiene/Gesturefy#79]
I love the addon very much, but selected text search still cannot satisfy me. So I would like to request some feature request on this term.

1. open the new search page on background tab;
2. Add several search engineers with different gestures simultaneously.

Thank you.

**Comment by Robbendebiene** [comment]
I completly understand the use case of different gestures for different actions. My approach to solve this, is by changing the one-to-one mapping list to a user defined list. So users can create their own list of gestures and assign any action (including its settings) to them.
Unfortunately this is not going to happen soon, due to the lack of time.

However I'll keep adding simple actions or options like the "open the new search page on background tab" if you still need it without the other feature.

**Comment by Robbendebiene** [comment]
> open the new search page on background tab;

an option is now available in Gesturefy version 1.1.13
