### ISSUE TITLE
Make Gesturefy use same gestures as FireGestures in default

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#8]
It just makes sense, when you want to replace it. I guess lot of users would be scared that it behaves differently and won't fiddle with the settings and just uninstall.

**Comment by Robbendebiene** [comment]
I completely understand your point and I think that my confusing statement about "replacing and mimicking" FireGestures led you to this conclusion. However if I wanted to mimic it perfectly I would have designed the exact same way and maybe even named it "FireGestures 2.0" or "FireGestures reloaded". Ofcourse from a usersperspective you are completely right, but I want the user to treat my addon as something new/different as it does not have the potential for a full replacement. Also I wanted to add a bit of my own zest to be honest :)

To answer some other points from your [review](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/reviews/881586/) , btw thanks for that :)

> Show action + Show gesture slowed the browsing experience for me a lot, after turning it off it's perfect (and it's also a different behaviour from FireGestures, it looks nice, but I'd prefer the status box instead - API limitation?)

For my experience the only thing thats really performance exhausting is the gesture path drawing, this is because I draw the path as smooth as possible what firegestures did not. But I have to admit, that it is a bit too much, so I think I'm going to decrease the CPU usage by half.
With the new API I can only mimic the staus box with html/css. But I decided to design it differently. However with the current styling preferences you can at least achieve something like this: ![style](https://user-images.githubusercontent.com/13716661/26922478-84f624be-4c3f-11e7-937e-f6f279b47604.png) by scaling the directions down, move them to the right and change the background color and opacity.

> No "Open this link in a new tab" gesture, but since it doesn't work even in FireGestures now I guess they blocked it.

It is planned for version 1.0.2 see this [issue](https://github.com/Robbendebiene/Gesturefy/issues/4) for more information.

> I would love rocker gestures, but API

Maybe it is possible to implement this, but since it's a different gesture behaviour don't expect this to happen very soon. You can create an extra issue for that if you want to, so I won't forget about it :)

**Comment by stmr** [comment]
Perfect! Thanks for fast and great response.

I will try the gesture and action overlays again, just to see :)
Closing this issue and making one for the rocker gestures
