### ISSUE TITLE
new gesture for incress/decress page number

### ISSUE THREAD

**Issue by ledemon** [Robbendebiene/Gesturefy#85]
"mouse gesture suite" for the older firefox 56 have gesture for incress/decress page number and should be nice keep that in the beginins of XXI century

**Comment by Robbendebiene** [comment]
I know some basics about this functionality, but can you explain me what happens if the url looks like this: https://github.com/Robbendebiene/Gesturefy/issues/ (no number at the end) and I run the decrease or increase action/gesture?

Does the number have to be at the end of the url like this: https://github.com/Robbendebiene/Gesturefy/issue/999?

**Comment by mity** [comment]
@Robbendebiene

As an user I expect something like the following:

1. Find last number in the URL (i.e. sequence of decimal digit characters). The number does not need to be at the end of the URL. (Consider e.g. `http://example.com/gallery/123.png` or `http://example.com/set12/index.html` or `http://example.com/gallery.php?page=123`)
2. If no such number is found, do nothing.
3. If found, increment/decrement the number and go the the new URL.

Some extra care should be likely taken to keep the count of digits when the number begins with one or more zero characters. For example, if the URL is e.g. `http://example.com/0010.png`, then the incremented one should be `http://example.com/0011.png` and not `http://example.com/11.png`; and similarly the decremented URL should be `http://example.com/0009.png` (note the number of leading zeros changes here).

**Comment by ledemon** [comment]
ok, the 'mouse gesture suite' let the user choose what part of the address is the progress count, I know that others addons choose automatic and a few cases the wrong part of the address.
The mechanism was show a popup with a textbox and the user mark the part of the text and accept, this is only the first time, isnt the best option but already is only one time. (probably make a persistent config to save the users choice for each site, but isn't necessary)
And need a third option to reset the count for possible wrong progression.

Is only one suggestion 😄

**Comment by Robbendebiene** [comment]
@mity Thanks for the detailed explanation. The only concern I have, is including the url queries.
It wouldn't work for http://example.com/gallery/123?size=50, since you recommend to increase/decrease the last number occurence. Queries in general can contain a lot of numbers which may be completely unrelated to some kind of pagination.

@ledemon Hmm sorry, but I highly tend to automate the whole process, due to the effort your suggestion would take.

**Comment by mity** [comment]
> The only concern I have, is including the url queries.
It wouldn't work for http://example.com/gallery/123?size=50, since you recommend to increase/decrease the last number occurence. Queries in general can contain a lot of numbers which may be completely unrelated to some kind of pagination.

I have no hard data about that. You know, the "last number" is just the most simple heuristics I came up with. Maybe it could be done so that the last number in the path takes precedence over any number in a query, i.e. that the number in a query would be incremented/decremented only if there is no number in the path.

But even when limiting it just to the path, it would be useful feature which I miss.

**Comment by Robbendebiene** [comment]
> Maybe it could be done so that the last number in the path takes precedence over any number in a query

This sounds like a good approach to me.

**Comment by liborfoltynek** [comment]
Hi, I was going to add this feature request too. 
From my point o view don't care of details. If there is no number in url, just ignore it. If there are more numbers, choose one of them. OK, it will be great if I can choose some pattern, like "at xyz.com domain use this pattern" but for me is more important to have anything sooner than a perfect functionality later.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/94de6b8f863006ea53231c31fed272ae4e630050

**Comment by ledemon** [comment]
thanks a lot
