### ISSUE TITLE
Option to change permissions

### ISSUE THREAD

**Issue by jorgusch** [Robbendebiene/Gesturefy#93]
I am not a developer and I do not know what the permissions actually do. It is a lot any many for this add-on and it is explained anywhere nor can I change it. It is also poorly done by FF itself not to centralise it (?) but please document and limit where possible.

**Comment by jdreesen** [comment]
You can find an explanation of the permissions on [AMO](https://addons.mozilla.org/de/firefox/addon/gesturefy/). You have to click on "Show more" in the "About this extension" section.

**Comment by jorgusch** [comment]
Hello,

 

Thanks, I was not aware this exits. 

 

Two examples: 

·  Read and modify bookmarks: There is an action which allows to bookmark the current tab/url.

·  Input data to the clipboard: There are some actions which allow to copy text or an image to the clipboard.

 

I do not want to use either function. Why is it not possible to revoke or opt-in into this functionality? When one activates a certain action, your app could ask for further permission. 

 

At least an opt-out option should be given.

 

Thanks

Georg

**Comment by Robbendebiene** [comment]
The explanation is simple. When I started programming this addon, the necessary [API ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions) was not implemented.
Of course I will implement this someday, but since it requires a lot of work and the code is completely open source, you should not expect this soon.

**Comment by Philippe734** [comment]
The permission "Input data to the clipboard" is not safe in my opinion. How to be ensure that no body from the authors receive data copy/paste from us ? In particular when user copy/past its login-password from keepass for example. Could you communicate what kind of data are send to the authors from users copy/paste ? I wish too revoke the permission "Input data to the clipboard" in order to prevent the leak of my passwords copy/paste. Any solution to revoke that permission will be appreciate.

**Comment by Robbendebiene** [comment]
Permissions are now minimized since [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0) (In the future even the session restore permission might be moved to an optional permission if Mozilla allows it)
